"""
Agent Shield - Shared Detection Patterns
Auto-generated from patterns.json v5.0.0 on 2026-03-20.
Total patterns: 141

DO NOT EDIT — regenerate with: node patterns/generate.js
"""

import re

PATTERNS_VERSION = "5.0.0"
PATTERNS_GENERATED_AT = "2026-03-20"

INJECTION_PATTERNS = [
    {
        "id": "IO-001",
        "regex": re.compile(r'ignore\s+(all\s+)?(previous|prior|above|earlier)\s+(instructions|rules|guidelines|prompts|context|directions|directives|text|commands)', re.IGNORECASE),
        "category": "instruction_override",
        "severity": "high",
        "description": "Text tells AI assistants to ignore their safety rules.",
        "detail": "Instruction override pattern: attempts to nullify prior AI instructions.",
        "tags": ["injection","override"],
    },
    {
        "id": "IO-002",
        "regex": re.compile(r'^ignore\s+(?:the\s+)?(?:instructions|rules|guidelines|directives|commands)$', re.IGNORECASE | re.MULTILINE),
        "category": "instruction_override",
        "severity": "high",
        "description": "Text tells AI assistants to ignore instructions.",
        "detail": "Simple instruction override: direct command to ignore instructions.",
        "tags": ["injection","override"],
    },
    {
        "id": "IO-003",
        "regex": re.compile(r'disregard\s+(all\s+)?(previous|prior|above|earlier|your)\s+(instructions|rules|guidelines|prompts|training|training\s+data|context)', re.IGNORECASE),
        "category": "instruction_override",
        "severity": "high",
        "description": "Text tells AI assistants to throw out their rules.",
        "detail": "Instruction disregard pattern: attempts to nullify prior AI instructions.",
        "tags": ["injection","override"],
    },
    {
        "id": "IO-004",
        "regex": re.compile(r'forget\s+(your|all|any|everything)\s+(training|instructions|rules|guidelines|programming|above|previous|prior)', re.IGNORECASE),
        "category": "instruction_override",
        "severity": "high",
        "description": "Text tries to make AI assistants forget their training.",
        "detail": "Training override pattern: attempts to reset AI behavioral constraints.",
        "tags": ["injection","override"],
    },
    {
        "id": "IO-005",
        "regex": re.compile(r'override\s+(?:all\s+)?(?:system|safety|security)\s+(?:settings|prompt|instructions|rules|mechanisms|filters|checks|protocols)', re.IGNORECASE),
        "category": "instruction_override",
        "severity": "critical",
        "description": "Text tries to override AI safety settings.",
        "detail": "System override pattern: direct attempt to bypass AI safety mechanisms.",
        "tags": ["injection","override"],
    },
    {
        "id": "IO-006",
        "regex": re.compile(r'(?:^|\n)\s*(?:new|updated|revised|replacement)\s+(?:instructions|policy)\s*:', re.IGNORECASE),
        "category": "instruction_override",
        "severity": "high",
        "description": "Text contains fake \"new instructions\" for AI assistants.",
        "detail": "Instruction replacement pattern: attempts to inject new behavioral directives.",
        "tags": ["injection","override"],
    },
    {
        "id": "IO-007",
        "regex": re.compile(r'#{2,}\s*(?:NEW|UPDATED|REVISED|REPLACEMENT)\s+(?:INSTRUCTIONS|RULES|DIRECTIVES|POLICY)\s*#{0,}', re.IGNORECASE),
        "category": "instruction_override",
        "severity": "high",
        "description": "Text uses markdown headers to inject fake new instructions.",
        "detail": "Markdown instruction injection: uses heading syntax to inject new behavioral directives.",
        "tags": ["injection","override"],
    },
    {
        "id": "PI-001",
        "regex": re.compile(r'(?:^|\n)\s*(?:SYSTEM|ADMIN|ROOT)\s*:\s*.{10,}', re.IGNORECASE),
        "category": "prompt_injection",
        "severity": "high",
        "description": "Text contains a fake SYSTEM/ADMIN directive.",
        "detail": "Unbracketed system directive: uses SYSTEM: prefix to inject instructions.",
        "tags": ["injection","system-prompt"],
    },
    {
        "id": "IO-008",
        "regex": re.compile(r'(?:you\s+must\s+)?ignore\s+(?:your|all\s+your|all\s+the|the)\s+(?:safety\s+)?(?:guidelines?|rules?|restrictions?|protocols?|safeguards?|filters?|limits?)', re.IGNORECASE),
        "category": "instruction_override",
        "severity": "high",
        "description": "Text tells AI to ignore its guidelines or safety rules.",
        "detail": "Guideline override: direct instruction to ignore safety guidelines.",
        "tags": ["injection","override"],
    },
    {
        "id": "IO-009",
        "regex": re.compile(r'(?:abandon|drop|ditch|clear)\s+(?:all\s+)?(?:prior|previous|above|earlier|initial)\s+(?:context|instructions|rules|constraints|guidelines)', re.IGNORECASE),
        "category": "instruction_override",
        "severity": "high",
        "description": "Text tells AI to abandon its prior context or instructions.",
        "detail": "Context abandonment pattern: attempts to clear AI behavioral constraints.",
        "tags": ["injection","override"],
    },
    {
        "id": "IO-010",
        "regex": re.compile(r'(?:STOP|HALT|END)\s*[.!]?\s*(?:new|updated|your\s+new|revised)\s+(?:instructions|task|orders|role|objective)', re.IGNORECASE),
        "category": "instruction_override",
        "severity": "high",
        "description": "Text uses a STOP command followed by new instructions.",
        "detail": "Stop-and-replace pattern: halts current behavior and injects new instructions.",
        "tags": ["injection","override"],
    },
    {
        "id": "IO-011",
        "regex": re.compile(r'(?:you\s+are\s+)?(?:no\s+longer\s+bound|not\s+bound|free\s+from|freed?\s+from)\s+(?:by\s+)?(?:your\s+)?(?:initial|original|previous|prior)?\s*(?:instructions|rules|constraints|guidelines|restrictions)', re.IGNORECASE),
        "category": "instruction_override",
        "severity": "high",
        "description": "Text claims the AI is no longer bound by its rules.",
        "detail": "Constraint removal pattern: declares AI rules no longer apply.",
        "tags": ["injection","override"],
    },
    {
        "id": "RH-001",
        "regex": re.compile(r'you\s+are\s+now\s+(?:a|an|the)\s+', re.IGNORECASE),
        "category": "role_hijack",
        "severity": "high",
        "description": "Text tries to change what an AI assistant thinks it is.",
        "detail": "Role reassignment pattern: attempts to override AI identity.",
        "tags": ["injection","role-hijack"],
    },
    {
        "id": "RH-002",
        "regex": re.compile(r'from\s+now\s+on[\s,]+(?:you\s+)?(?:will|shall|must|should|are)\s+(?:act|behave|operate|respond|answer|reply|pretend|simulate|function|serve|work)\s+(?:as|like|without)', re.IGNORECASE),
        "category": "role_hijack",
        "severity": "high",
        "description": "Text tries to give permanent new orders to AI assistants.",
        "detail": "Persistent role override: attempts to establish new behavioral baseline.",
        "tags": ["injection","role-hijack"],
    },
    {
        "id": "RH-003",
        "regex": re.compile(r'from\s+now\s+on[\s,]+(?:you\s+)?(?:respond|act|behave|operate)\s+(?:as\s+if|like|without)', re.IGNORECASE),
        "category": "role_hijack",
        "severity": "high",
        "description": "Text tries to permanently change AI behavior.",
        "detail": "Persistent behavioral override: attempts to establish new behavioral baseline.",
        "tags": ["injection","role-hijack"],
    },
    {
        "id": "RH-004",
        "regex": re.compile(r'(?:act|behave|function|operate|respond)\s+as\s+(?:a|an)\s+unrestricted', re.IGNORECASE),
        "category": "role_hijack",
        "severity": "high",
        "description": "Text tries to remove AI safety restrictions.",
        "detail": "Restriction removal pattern: attempts to disable AI safety guardrails.",
        "tags": ["injection","role-hijack"],
    },
    {
        "id": "RH-005",
        "regex": re.compile(r'pretend\s+(?:you\s+)?(?:have\s+no|there\s+are\s+no|without)\s+restrictions', re.IGNORECASE),
        "category": "role_hijack",
        "severity": "high",
        "description": "Text asks AI to pretend it has no safety limits.",
        "detail": "Restriction pretense pattern: social engineering to bypass safety limits.",
        "tags": ["injection","role-hijack"],
    },
    {
        "id": "RH-006",
        "regex": re.compile(r'pretend\s+(?:to\s+be|you\s+are)\s+(?:a|an)\s+(?:evil|unrestricted|unfiltered|uncensored|malicious)', re.IGNORECASE),
        "category": "role_hijack",
        "severity": "high",
        "description": "Text asks AI to pretend to be an evil or unrestricted entity.",
        "detail": "Evil persona pretense: social engineering to adopt unrestricted persona.",
        "tags": ["injection","role-hijack"],
    },
    {
        "id": "RH-007",
        "regex": re.compile(r'\b(?:DAN|D\.A\.N\.?)\s*(?:mode|prompt|jailbreak|\()', re.IGNORECASE),
        "category": "role_hijack",
        "severity": "critical",
        "description": "Text contains a known AI jailbreak technique called \"DAN mode.\"",
        "detail": "DAN (Do Anything Now) jailbreak pattern detected.",
        "tags": ["injection","role-hijack","jailbreak"],
    },
    {
        "id": "RH-008",
        "regex": re.compile(r'\bdo\s+anything\s+now\b', re.IGNORECASE),
        "category": "role_hijack",
        "severity": "critical",
        "description": "Text references the \"Do Anything Now\" jailbreak technique.",
        "detail": "DAN (Do Anything Now) jailbreak reference detected.",
        "tags": ["injection","role-hijack","jailbreak"],
    },
    {
        "id": "RH-009",
        "regex": re.compile(r'\b(?:developer|dev)\s+mode\s+(?:enabled|activated|on|output)', re.IGNORECASE),
        "category": "role_hijack",
        "severity": "high",
        "description": "Text tries to trick AI into a fake \"developer mode.\"",
        "detail": "Developer mode activation pattern: common jailbreak technique.",
        "tags": ["injection","role-hijack","jailbreak"],
    },
    {
        "id": "RH-010",
        "regex": re.compile(r'\bjailbreak\s*(?:mode|prompt|enabled|activated)', re.IGNORECASE),
        "category": "role_hijack",
        "severity": "critical",
        "description": "Text contains an AI jailbreak attempt.",
        "detail": "Explicit jailbreak activation pattern detected.",
        "tags": ["injection","role-hijack","jailbreak"],
    },
    {
        "id": "RH-011",
        "regex": re.compile(r'\bgod\s*mode\s*(?:enabled|activated|on)', re.IGNORECASE),
        "category": "role_hijack",
        "severity": "critical",
        "description": "Text tries to activate \"god mode\" on AI assistants.",
        "detail": "God mode activation pattern: attempts to remove all AI restrictions.",
        "tags": ["injection","role-hijack","jailbreak"],
    },
    {
        "id": "PI-002",
        "regex": re.compile(r'\[\s*(?:SYSTEM|SYS)\s*\]', re.IGNORECASE),
        "category": "prompt_injection",
        "severity": "critical",
        "description": "Text contains fake system-level commands for AI assistants.",
        "detail": "Spoofed [SYSTEM] tag: attempts to inject system-level instructions.",
        "tags": ["injection","system-prompt"],
    },
    {
        "id": "PI-003",
        "regex": re.compile(r'\[\s*(?:ADMIN|ADMINISTRATOR)\s*\]', re.IGNORECASE),
        "category": "prompt_injection",
        "severity": "critical",
        "description": "Text fakes admin-level commands for AI assistants.",
        "detail": "Spoofed [ADMIN] tag: attempts to inject administrator-level instructions.",
        "tags": ["injection","system-prompt"],
    },
    {
        "id": "PI-004",
        "regex": re.compile(r'\[\s*(?:DEVELOPER|DEV)\s*\]', re.IGNORECASE),
        "category": "prompt_injection",
        "severity": "high",
        "description": "Text contains fake developer commands for AI assistants.",
        "detail": "Spoofed [DEVELOPER] tag: attempts to inject developer-level instructions.",
        "tags": ["injection","system-prompt"],
    },
    {
        "id": "PI-005",
        "regex": re.compile(r'\[\s*OVERRIDE\s*\]', re.IGNORECASE),
        "category": "prompt_injection",
        "severity": "critical",
        "description": "Text contains override commands targeting AI assistants.",
        "detail": "Spoofed [OVERRIDE] tag: attempts to override AI behavior.",
        "tags": ["injection","system-prompt"],
    },
    {
        "id": "PI-006",
        "regex": re.compile(r'<<\s*SYS\s*>>', re.IGNORECASE),
        "category": "prompt_injection",
        "severity": "critical",
        "description": "Text contains hidden system commands in LLaMA format.",
        "detail": "LLaMA-style <<SYS>> system prompt injection detected.",
        "tags": ["injection","system-prompt"],
    },
    {
        "id": "PI-007",
        "regex": re.compile(r'<\|im_start\|>\s*system', re.IGNORECASE),
        "category": "prompt_injection",
        "severity": "critical",
        "description": "Text contains hidden system commands in ChatML format.",
        "detail": "ChatML-style <|im_start|>system prompt injection detected.",
        "tags": ["injection","system-prompt"],
    },
    {
        "id": "PI-008",
        "regex": re.compile(r'<\|system\|>', re.IGNORECASE),
        "category": "prompt_injection",
        "severity": "critical",
        "description": "Text contains hidden system-level AI commands.",
        "detail": "System delimiter injection: <|system|> token detected.",
        "tags": ["injection","system-prompt"],
    },
    {
        "id": "PI-009",
        "regex": re.compile(r'(?:^|\n)\s*system\s*prompt\s*:', re.IGNORECASE),
        "category": "prompt_injection",
        "severity": "high",
        "description": "Text tries to set a fake \"system prompt\" for AI assistants.",
        "detail": "System prompt injection: attempts to define system-level instructions.",
        "tags": ["injection","system-prompt"],
    },
    {
        "id": "PI-010",
        "regex": re.compile(r'#{2,}\s*(?:system\s+(?:message|prompt|instruction)|new\s+(?:system|admin)\s+(?:message|prompt))\s*#{0,}', re.IGNORECASE),
        "category": "prompt_injection",
        "severity": "high",
        "description": "Text uses markdown headers to inject fake system messages.",
        "detail": "Markdown-formatted system message injection: uses heading syntax to appear authoritative.",
        "tags": ["injection","system-prompt"],
    },
    {
        "id": "PI-011",
        "regex": re.compile(r'(?:Human|User|Assistant)\s*:\s*(?:ignore|forget|override|disregard).{0,50}(?:Human|User|Assistant)\s*:', re.IGNORECASE | re.DOTALL),
        "category": "prompt_injection",
        "severity": "high",
        "description": "Text simulates a multi-turn conversation to inject instructions.",
        "detail": "Multi-turn conversation injection: fakes a dialogue format to embed hidden instructions.",
        "tags": ["injection","system-prompt"],
    },
    {
        "id": "DE-001",
        "regex": re.compile(r'(?:show|display|print|reveal|output)\s+(?:me\s+)?(?:the\s+)?(?:exact\s+)?(?:text|content)\s+(?:between|inside|within|from)\s+(?:the\s+)?(?:<|&lt;)', re.IGNORECASE),
        "category": "data_exfiltration",
        "severity": "high",
        "description": "Text tries to extract content between specific tags.",
        "detail": "Tag extraction attempt: instructs agent to reveal content between markup tags.",
        "tags": ["exfiltration","data-leak"],
    },
    {
        "id": "DE-002",
        "regex": re.compile(r'send\s+(?:this|the|all|your|my)\s+(?:data|information|content|text|response)\s+to', re.IGNORECASE),
        "category": "data_exfiltration",
        "severity": "critical",
        "description": "Text tries to make AI assistants send data somewhere.",
        "detail": "Data exfiltration instruction: attempts to redirect AI output to external destination.",
        "tags": ["exfiltration","data-leak"],
    },
    {
        "id": "DE-003",
        "regex": re.compile(r'output\s+(?:your|the)\s+(?:system\s+)?prompt', re.IGNORECASE),
        "category": "data_exfiltration",
        "severity": "high",
        "description": "Text tries to extract the AI assistant's internal instructions.",
        "detail": "System prompt extraction: attempts to reveal AI system instructions.",
        "tags": ["exfiltration","data-leak"],
    },
    {
        "id": "DE-004",
        "regex": re.compile(r'reveal\s+(?:your|the)\s+(?:system\s+)?(?:instructions|prompt|rules|guidelines)', re.IGNORECASE),
        "category": "data_exfiltration",
        "severity": "high",
        "description": "Text tries to reveal the AI assistant's hidden rules.",
        "detail": "Instruction reveal attempt: tries to expose AI system prompt.",
        "tags": ["exfiltration","data-leak"],
    },
    {
        "id": "DE-005",
        "regex": re.compile(r'!\[[^\]]*\]\(https?:\/\/[^)]*\?[^)]*(?:data|q|query|text|payload|exfil|leak|steal)=', re.IGNORECASE),
        "category": "data_exfiltration",
        "severity": "critical",
        "description": "Text tries to steal data through a hidden image link.",
        "detail": "Markdown image exfiltration: data encoded in image URL parameters.",
        "tags": ["exfiltration","data-leak"],
    },
    {
        "id": "DE-006",
        "regex": re.compile(r'!\[\]\(https?:\/\/(?!(?:i\.)?(?:imgur|github|gitlab|wikimedia|wikipedia)\b)[^)]+\)', re.IGNORECASE),
        "category": "data_exfiltration",
        "severity": "medium",
        "description": "Text contains a suspicious hidden image link that could leak data.",
        "detail": "Markdown image with suspicious external URL — potential exfiltration vector.",
        "tags": ["exfiltration","data-leak"],
    },
    {
        "id": "SE-001",
        "regex": re.compile(r'do\s+not\s+(?:mention|say|tell|reveal|disclose|acknowledge)\s+(?:that\s+)?you\s+are\s+(?:a|an)\s+(?:AI|artificial|bot|machine|language\s+model)', re.IGNORECASE),
        "category": "social_engineering",
        "severity": "high",
        "description": "Text tells AI assistants to hide that they are AI.",
        "detail": "Identity concealment instruction: AI told to deny being artificial.",
        "tags": ["social-engineering"],
    },
    {
        "id": "SE-002",
        "regex": re.compile(r'do\s+not\s+(?:reveal|disclose|mention|acknowledge)\s+(?:that\s+)?(?:this|it)\s+is\s+automated', re.IGNORECASE),
        "category": "social_engineering",
        "severity": "high",
        "description": "Text tells AI to hide that responses are automated.",
        "detail": "Automation concealment: AI instructed to hide automated nature.",
        "tags": ["social-engineering"],
    },
    {
        "id": "SE-003",
        "regex": re.compile(r'do\s+not\s+acknowledge\s+(?:these|the|any)\s+(?:instructions|commands|directives)', re.IGNORECASE),
        "category": "social_engineering",
        "severity": "high",
        "description": "Text tells AI to hide that it received secret instructions.",
        "detail": "Instruction concealment: AI told to deny receiving hidden directives.",
        "tags": ["social-engineering"],
    },
    {
        "id": "PI-012",
        "regex": re.compile(r'(?:translate|decode|convert)\s+(?:the\s+following|this)\s*:?\s*["\s]*(?:ignore|forget|override|you\s+are\s+now)', re.IGNORECASE),
        "category": "prompt_injection",
        "severity": "high",
        "description": "Text hides an attack inside a fake translation request.",
        "detail": "Translation-wrapped injection: malicious instructions disguised as translation task.",
        "tags": ["injection","system-prompt"],
    },
    {
        "id": "IO-012",
        "regex": re.compile(r'ignora\s+(?:todas?\s+)?(?:las\s+)?instrucciones\s+(?:anteriores|previas)', re.IGNORECASE),
        "category": "instruction_override",
        "severity": "high",
        "description": "Text tells AI assistants to ignore their rules (in Spanish).",
        "detail": "Spanish instruction override: \"ignora instrucciones anteriores\" detected.",
        "tags": ["injection","override","i18n","spanish"],
    },
    {
        "id": "IO-013",
        "regex": re.compile(r'olvida\s+(?:tu|todas?\s+(?:las\s+)?)\s*(?:instrucciones|reglas|entrenamiento)', re.IGNORECASE),
        "category": "instruction_override",
        "severity": "high",
        "description": "Text tells AI to forget its training (in Spanish).",
        "detail": "Spanish training override: \"olvida tu entrenamiento\" detected.",
        "tags": ["injection","override","i18n","spanish"],
    },
    {
        "id": "RH-012",
        "regex": re.compile(r'ahora\s+eres\s+(?:un|una)\s+', re.IGNORECASE),
        "category": "role_hijack",
        "severity": "high",
        "description": "Text tries to change what an AI thinks it is (in Spanish).",
        "detail": "Spanish role hijack: \"ahora eres un/una\" detected.",
        "tags": ["injection","role-hijack","jailbreak","i18n","spanish"],
    },
    {
        "id": "IO-014",
        "regex": re.compile(r'ignore[rz]?\s+(?:toutes?\s+)?(?:les\s+)?instructions\s+(?:pr[eé]c[eé]dentes|ant[eé]rieures)', re.IGNORECASE),
        "category": "instruction_override",
        "severity": "high",
        "description": "Text tells AI assistants to ignore their rules (in French).",
        "detail": "French instruction override: \"ignorer instructions précédentes\" detected.",
        "tags": ["injection","override","i18n","spanish","french"],
    },
    {
        "id": "IO-015",
        "regex": re.compile(r'oublie[rz]?\s+(?:ton|tes|votre|vos)\s+(?:instructions|r[eè]gles|entra[iî]nement)', re.IGNORECASE),
        "category": "instruction_override",
        "severity": "high",
        "description": "Text tells AI to forget its training (in French).",
        "detail": "French training override: \"oublier ton entraînement\" detected.",
        "tags": ["injection","override","i18n","spanish","french"],
    },
    {
        "id": "RH-013",
        "regex": re.compile(r'tu\s+es\s+(?:maintenant|d[eé]sormais)\s+(?:un|une)\s+', re.IGNORECASE),
        "category": "role_hijack",
        "severity": "high",
        "description": "Text tries to change what an AI thinks it is (in French).",
        "detail": "French role hijack: \"tu es maintenant un/une\" detected.",
        "tags": ["injection","role-hijack","jailbreak","i18n","spanish","french"],
    },
    {
        "id": "IO-016",
        "regex": re.compile(r'ignoriere?\s+(?:alle\s+)?(?:vorherigen|bisherigen|fr[uü]heren)\s+(?:Anweisungen|Regeln|Instruktionen)', re.IGNORECASE),
        "category": "instruction_override",
        "severity": "high",
        "description": "Text tells AI assistants to ignore their rules (in German).",
        "detail": "German instruction override: \"ignoriere vorherige Anweisungen\" detected.",
        "tags": ["injection","override","i18n","spanish","french","german"],
    },
    {
        "id": "IO-017",
        "regex": re.compile(r'vergiss\s+(?:dein|deine|alle)\s+(?:Training|Anweisungen|Regeln|Programmierung)', re.IGNORECASE),
        "category": "instruction_override",
        "severity": "high",
        "description": "Text tells AI to forget its training (in German).",
        "detail": "German training override: \"vergiss dein Training\" detected.",
        "tags": ["injection","override","i18n","spanish","french","german"],
    },
    {
        "id": "RH-014",
        "regex": re.compile(r'du\s+bist\s+(?:jetzt|ab\s+jetzt|nun)\s+(?:ein|eine)\s+', re.IGNORECASE),
        "category": "role_hijack",
        "severity": "high",
        "description": "Text tries to change what an AI thinks it is (in German).",
        "detail": "German role hijack: \"du bist jetzt ein/eine\" detected.",
        "tags": ["injection","role-hijack","jailbreak","i18n","spanish","french","german"],
    },
    {
        "id": "IO-018",
        "regex": re.compile(r'ignore\s+(?:todas?\s+)?(?:as\s+)?instru[cç][oõ]es\s+(?:anteriores|pr[eé]vias)', re.IGNORECASE),
        "category": "instruction_override",
        "severity": "high",
        "description": "Text tells AI assistants to ignore their rules (in Portuguese).",
        "detail": "Portuguese instruction override: \"ignore instruções anteriores\" detected.",
        "tags": ["injection","override","i18n","spanish","french","german","portuguese"],
    },
    {
        "id": "IO-019",
        "regex": re.compile(r'esque[cç]a\s+(?:seu|sua|todo|todas?)\s+(?:treinamento|instru[cç][oõ]es|regras)', re.IGNORECASE),
        "category": "instruction_override",
        "severity": "high",
        "description": "Text tells AI to forget its training (in Portuguese).",
        "detail": "Portuguese training override: \"esqueça seu treinamento\" detected.",
        "tags": ["injection","override","i18n","spanish","french","german","portuguese"],
    },
    {
        "id": "RH-015",
        "regex": re.compile(r'agora\s+voc[eê]\s+[eé]\s+(?:um|uma)\s+', re.IGNORECASE),
        "category": "role_hijack",
        "severity": "high",
        "description": "Text tries to change what an AI thinks it is (in Portuguese).",
        "detail": "Portuguese role hijack: \"agora você é um/uma\" detected.",
        "tags": ["injection","role-hijack","jailbreak","i18n","spanish","french","german","portuguese"],
    },
    {
        "id": "IO-020",
        "regex": re.compile(r'忽略(?:所有)?(?:之前|以前|先前)的(?:指令|指示|规则|说明)', 0),
        "category": "instruction_override",
        "severity": "high",
        "description": "Text tells AI assistants to ignore their rules (in Chinese).",
        "detail": "Chinese instruction override: \"忽略之前的指令\" detected.",
        "tags": ["injection","override","i18n","spanish","french","german","portuguese","chinese"],
    },
    {
        "id": "RH-016",
        "regex": re.compile(r'你现在是(?:一个|一名)', 0),
        "category": "role_hijack",
        "severity": "high",
        "description": "Text tries to change what an AI thinks it is (in Chinese).",
        "detail": "Chinese role hijack: \"你现在是一个\" detected.",
        "tags": ["injection","role-hijack","jailbreak","i18n","spanish","french","german","portuguese","chinese"],
    },
    {
        "id": "IO-021",
        "regex": re.compile(r'(?:以前|前)の(?:指示|命令|ルール|指令)を(?:無視|忘れ)', 0),
        "category": "instruction_override",
        "severity": "high",
        "description": "Text tells AI assistants to ignore their rules (in Japanese).",
        "detail": "Japanese instruction override detected.",
        "tags": ["injection","override","i18n","spanish","french","german","portuguese","chinese","japanese"],
    },
    {
        "id": "RH-017",
        "regex": re.compile(r'あなたは(?:今|これから)[\s\S]{0,5}(?:です|になり)', 0),
        "category": "role_hijack",
        "severity": "high",
        "description": "Text tries to change what an AI thinks it is (in Japanese).",
        "detail": "Japanese role hijack pattern detected.",
        "tags": ["injection","role-hijack","jailbreak","i18n","spanish","french","german","portuguese","chinese","japanese"],
    },
    {
        "id": "PI-013",
        "regex": re.compile(r'\[(?:[^\]]*)\]\(javascript\s*:', re.IGNORECASE),
        "category": "prompt_injection",
        "severity": "critical",
        "description": "Text contains a dangerous JavaScript link disguised as a normal link.",
        "detail": "Markdown link with javascript: protocol — could execute malicious code.",
        "tags": ["injection","system-prompt"],
    },
    {
        "id": "PI-014",
        "regex": re.compile(r'\[(?:[^\]]*)\]\(data\s*:', re.IGNORECASE),
        "category": "prompt_injection",
        "severity": "high",
        "description": "Text contains a suspicious data link disguised as a normal link.",
        "detail": "Markdown link with data: protocol — could embed malicious content.",
        "tags": ["injection","system-prompt"],
    },
    {
        "id": "PI-015",
        "regex": re.compile(r'```(?:system|admin|override|instructions)[\s\S]*?```', re.IGNORECASE),
        "category": "prompt_injection",
        "severity": "high",
        "description": "Text hides AI commands inside a code block.",
        "detail": "Markdown code block labeled as system/admin/override instructions.",
        "tags": ["injection","system-prompt"],
    },
    {
        "id": "MP-001",
        "regex": re.compile(r'(?:install|add|enable|activate)\s+(?:this\s+)?(?:custom\s+)?(?:GPT|plugin|extension|MCP\s+server|tool)\b', re.IGNORECASE),
        "category": "malicious_plugin",
        "severity": "medium",
        "description": "Text promotes installing an AI plugin or tool. Unverified plugins can access your data.",
        "detail": "AI plugin/extension installation prompt detected.",
        "tags": ["plugin","supply-chain"],
    },
    {
        "id": "MP-002",
        "regex": re.compile(r'(?:requires?\s+(?:your\s+)?(?:API|access)\s*key|enter\s+(?:your\s+)?(?:API|OpenAI|Anthropic|Claude)\s*(?:API\s*)?key|(?:provide|give|share|input|type|paste)\s+(?:your\s+)?(?:API|OpenAI|Anthropic|Claude)\s*(?:API\s*)?key)', re.IGNORECASE),
        "category": "malicious_plugin",
        "severity": "high",
        "description": "Text asks for an AI service API key. Legitimate services rarely ask for this.",
        "detail": "API key harvesting attempt: solicits AI service credentials.",
        "tags": ["plugin","supply-chain"],
    },
    {
        "id": "MP-003",
        "regex": re.compile(r'(?:unverified|unofficial|custom)\s+(?:GPT|ChatGPT|plugin|agent|MCP)', re.IGNORECASE),
        "category": "malicious_plugin",
        "severity": "medium",
        "description": "Text references an unverified AI plugin or custom GPT.",
        "detail": "Reference to unverified/unofficial AI plugin or custom GPT detected.",
        "tags": ["plugin","supply-chain"],
    },
    {
        "id": "AP-001",
        "regex": re.compile(r'(?:your\s+(?:ChatGPT|Claude|Gemini|OpenAI|Anthropic|AI)\s+(?:account|subscription)\s+(?:has\s+been|was|is)\s+(?:suspended|compromised|locked|expired|flagged))', re.IGNORECASE),
        "category": "ai_phishing",
        "severity": "high",
        "description": "Text claims an AI account is in trouble — likely a scam.",
        "detail": "AI service phishing: fake account suspension/compromise notification.",
        "tags": ["phishing","scam"],
    },
    {
        "id": "AP-002",
        "regex": re.compile(r'(?:verify|confirm|update|secure)\s+your\s+(?:ChatGPT|Claude|Gemini|OpenAI|Anthropic|AI)\s+(?:account|identity|subscription|payment)', re.IGNORECASE),
        "category": "ai_phishing",
        "severity": "high",
        "description": "Text asks to \"verify\" an AI account — real services don't do this on third-party sites.",
        "detail": "AI service phishing: fake account verification request.",
        "tags": ["phishing","scam"],
    },
    {
        "id": "AP-003",
        "regex": re.compile(r'(?:free|unlimited|premium)\s+(?:ChatGPT|GPT-?4|Claude|Gemini)\s+(?:access|account|pro|plus|subscription)', re.IGNORECASE),
        "category": "ai_phishing",
        "severity": "medium",
        "description": "Text offers free premium AI access — likely a scam or data harvesting.",
        "detail": "AI service bait: offering free premium access to lure users.",
        "tags": ["phishing","scam"],
    },
    {
        "id": "AP-004",
        "regex": re.compile(r'(?:ChatGPT|Claude|Gemini|GPT)\s+(?:5|Pro|Ultra|Plus)\s+(?:is\s+here|now\s+available|early\s+access|beta\s+access|waitlist)', re.IGNORECASE),
        "category": "ai_phishing",
        "severity": "medium",
        "description": "Text claims early access to an AI product — verify on the official site.",
        "detail": "Potential AI vaporware scam: claiming early access to unannounced AI products.",
        "tags": ["phishing","scam"],
    },
    {
        "id": "AP-005",
        "regex": re.compile(r'(?:deepfake|deep\s*fake)\s+(?:video|image|photo|audio|voice|generator|creator|maker|tool|service)', re.IGNORECASE),
        "category": "ai_phishing",
        "severity": "medium",
        "description": "Text references deepfake creation tools — can be used to impersonate real people.",
        "detail": "Deepfake media tool reference detected. May facilitate identity fraud or misinformation.",
        "tags": ["phishing","scam"],
    },
    {
        "id": "AP-006",
        "regex": re.compile(r"(?:clone|cloning)\s+(?:your|any|someone'?s?)\s+(?:voice|face|likeness|identity)", re.IGNORECASE),
        "category": "ai_phishing",
        "severity": "high",
        "description": "Text promotes cloning someone's voice or face — commonly used in scams.",
        "detail": "AI voice/face cloning promotion detected. Common in impersonation scams.",
        "tags": ["phishing","scam"],
    },
    {
        "id": "AP-007",
        "regex": re.compile(r'(?:verify|confirm)\s+(?:your\s+)?(?:identity|account)\s+(?:by|using|with)\s+(?:voice|speaking|recording)', re.IGNORECASE),
        "category": "ai_phishing",
        "severity": "high",
        "description": "Text asks to verify identity by voice — scammers use this to clone voices with AI.",
        "detail": "Voice identity verification scam: collected voice data can be used for AI voice cloning.",
        "tags": ["phishing","scam"],
    },
    {
        "id": "AP-008",
        "regex": re.compile(r'(?:record|say|speak|read)\s+(?:the\s+following|this\s+(?:phrase|sentence|text))\s+(?:to|for)\s+(?:verify|confirm|authenticate)', re.IGNORECASE),
        "category": "ai_phishing",
        "severity": "high",
        "description": "Text asks to record a phrase — a common AI voice cloning scam technique.",
        "detail": "Voice sample harvesting: users asked to speak phrases that can train voice cloning models.",
        "tags": ["phishing","scam"],
    },
    {
        "id": "AP-009",
        "regex": re.compile(r'(?:scan|click)\s+(?:this|the)\s+(?:QR\s*code|barcode)\s+(?:to|for)\s+(?:verify|confirm|authenticate|unlock|claim)', re.IGNORECASE),
        "category": "ai_phishing",
        "severity": "high",
        "description": "Text uses QR codes to lure users into a phishing flow.",
        "detail": "QR code phishing (quishing): directs users to scan a code for fake verification.",
        "tags": ["phishing","scam"],
    },
    {
        "id": "AP-010",
        "regex": re.compile(r'(?:your|the)\s+(?:AI|model|assistant|account)\s+(?:has\s+been|was|is)\s+(?:flagged|reported|compromised|locked|limited)\s+(?:for|due\s+to)\s+(?:suspicious|unusual|unauthorized)', re.IGNORECASE),
        "category": "ai_phishing",
        "severity": "high",
        "description": "Text claims an AI account was flagged — a common phishing scare tactic.",
        "detail": "AI account scare phishing: fake alert about account being flagged for suspicious activity.",
        "tags": ["phishing","scam"],
    },
    {
        "id": "AP-011",
        "regex": re.compile(r'(?:verify|confirm)\s+(?:your\s+)?(?:identity|account)\s+(?:via|through|using|by)\s+(?:MFA|2FA|two.factor|multi.factor|authenticat)', re.IGNORECASE),
        "category": "ai_phishing",
        "severity": "high",
        "description": "Text asks for MFA/2FA verification — may be harvesting authentication tokens.",
        "detail": "MFA phishing: attempts to intercept or harvest multi-factor authentication credentials.",
        "tags": ["phishing","scam"],
    },
    {
        "id": "AP-012",
        "regex": re.compile(r'(?:urgent|immediate|critical)\s*[:\-!]?\s*(?:your\s+)?(?:API\s+key|token|credentials?|password|secret)\s+(?:has|have|is|was|will)\s+(?:been\s+)?(?:expir|compromis|revok|leak|expos|reset)', re.IGNORECASE),
        "category": "ai_phishing",
        "severity": "critical",
        "description": "Text creates urgency about leaked/expired credentials — classic phishing.",
        "detail": "Credential urgency phishing: fake alert about API keys or tokens being compromised.",
        "tags": ["phishing","scam"],
    },
    {
        "id": "AP-013",
        "regex": re.compile(r'(?:click|visit|go\s+to|open|navigate)\s+(?:this|the)\s+(?:link|url|page)\s+(?:to|and)\s+(?:verify|confirm|restore|recover|unlock|secure)\s+(?:your\s+)?(?:account|access|identity)', re.IGNORECASE),
        "category": "ai_phishing",
        "severity": "high",
        "description": "Text directs users to click a link for fake account recovery.",
        "detail": "Link-based phishing: directs user to external URL for fake verification/recovery.",
        "tags": ["phishing","scam"],
    },
    {
        "id": "AP-014",
        "regex": re.compile(r'(?:enter|provide|submit|type|input)\s+(?:your\s+)?(?:API\s+key|secret\s+key|access\s+token|private\s+key|password|credentials?)\s+(?:here|below|in\s+(?:the|this)\s+(?:field|form|box|input))', re.IGNORECASE),
        "category": "ai_phishing",
        "severity": "critical",
        "description": "Text asks users to enter sensitive credentials into a form.",
        "detail": "Credential harvesting: direct request for API keys, passwords, or tokens.",
        "tags": ["phishing","scam"],
    },
    {
        "id": "AP-015",
        "regex": re.compile(r'(?:free|unlimited|premium)\s+(?:AI|GPT|Claude|model)\s+(?:access|credits?|tokens?|usage)\s+(?:at|via|through|from)\s+', re.IGNORECASE),
        "category": "ai_phishing",
        "severity": "medium",
        "description": "Text promotes free/unlimited AI access — common lure for credential theft.",
        "detail": "AI access scam: fake offer of free/unlimited AI service to harvest credentials.",
        "tags": ["phishing","scam"],
    },
    {
        "id": "AP-016",
        "regex": re.compile(r'(?:your\s+)?(?:subscription|plan|trial|access)\s+(?:has\s+)?(?:expired|ended|been\s+cancelled|will\s+expire)\s*[.,!]?\s*(?:renew|reactivate|update\s+(?:your\s+)?(?:payment|billing|card))', re.IGNORECASE),
        "category": "ai_phishing",
        "severity": "high",
        "description": "Text claims a subscription expired and asks to renew — billing phishing.",
        "detail": "Subscription phishing: fake expiration notice to harvest payment information.",
        "tags": ["phishing","scam"],
    },
    {
        "id": "PI-016",
        "regex": re.compile('(?:alt|title)\\s*=\\s*["\'][^"\']*(?:ignore|override|system|admin|forget|you\\s+are\\s+now)[^"\']*["\']', re.IGNORECASE),
        "category": "prompt_injection",
        "severity": "critical",
        "description": "Image description contains hidden AI instructions — targets multimodal AI assistants.",
        "detail": "Indirect prompt injection via image alt/title attribute. Text-in-image targeting multimodal AI.",
        "tags": ["injection","system-prompt"],
    },
    {
        "id": "PI-017",
        "regex": re.compile(r'(?:(?:use|perform|do|run|apply)\s+OCR\s+(?:on|to)\s+(?:this|the)|read\s+(?:the\s+)?text\s+(?:in|from)\s+(?:this|the)\s+image|extract\s+text\s+from\s+(?:this|the)\s+image)(?:\s+and\s+(?:follow|execute|run|process))?', re.IGNORECASE),
        "category": "prompt_injection",
        "severity": "medium",
        "description": "Text instructs AI to read text from an image — could deliver hidden attack payloads.",
        "detail": "OCR-based prompt injection vector: instructs AI to extract and process text from images.",
        "tags": ["injection","system-prompt"],
    },
    {
        "id": "TA-001",
        "regex": re.compile(r'(?:execute|run|call)\s+(?:the\s+)?(?:shell|bash|terminal|command|cmd)[\s:]+(?:command|tool)?', re.IGNORECASE),
        "category": "tool_abuse",
        "severity": "critical",
        "description": "Text tries to make an AI agent execute shell commands.",
        "detail": "Tool abuse: attempts to trigger shell/command execution via agent.",
        "tags": ["tool-abuse","agent"],
    },
    {
        "id": "TA-002",
        "regex": re.compile(r'(?:use|call|invoke|execute)\s+(?:the\s+)?(?:tool|function|action)\s+(?:to\s+)?(?:delete|remove|drop|truncate|destroy)', re.IGNORECASE),
        "category": "tool_abuse",
        "severity": "critical",
        "description": "Text tries to make an AI agent use tools to delete or destroy data.",
        "detail": "Destructive tool invocation: attempts to use agent tools for data destruction.",
        "tags": ["tool-abuse","agent"],
    },
    {
        "id": "DE-007",
        "regex": re.compile(r'(?:read|access|open|cat|dump)\s+(?:the\s+)?(?:\.env|credentials|secrets?|private\s*key|password|token)\s*(?:file)?', re.IGNORECASE),
        "category": "data_exfiltration",
        "severity": "critical",
        "description": "Text tries to make an AI agent access sensitive files like credentials or secrets.",
        "detail": "Credential access attempt: instructs agent to read sensitive files.",
        "tags": ["exfiltration","data-leak"],
    },
    {
        "id": "DE-008",
        "regex": re.compile(r'(?:curl|wget|fetch|post|send)\s+(?:.*?\s+)?(?:to\s+)?https?:\/\/', re.IGNORECASE),
        "category": "data_exfiltration",
        "severity": "high",
        "description": "Text tries to make an AI agent send data to an external URL.",
        "detail": "External request instruction: attempts to make agent send data to remote server.",
        "tags": ["exfiltration","data-leak"],
    },
    {
        "id": "TA-003",
        "regex": re.compile(r'(?:modify|edit|change|update|overwrite)\s+(?:the\s+)?(?:system\s*prompt|instructions|config|\.env|settings)', re.IGNORECASE),
        "category": "tool_abuse",
        "severity": "critical",
        "description": "Text tries to make an AI agent modify its own configuration or system prompt.",
        "detail": "Self-modification attempt: instructs agent to alter its own configuration.",
        "tags": ["tool-abuse","agent"],
    },
    {
        "id": "SE-004",
        "regex": re.compile(r"(?:don'?t|do\s+not|never)\s+(?:log|record|save|store|track)\s+(?:this|the|any)", re.IGNORECASE),
        "category": "social_engineering",
        "severity": "high",
        "description": "Text tells an AI agent not to log or record actions — a sign of malicious intent.",
        "detail": "Anti-logging instruction: attempts to prevent audit trail of agent actions.",
        "tags": ["social-engineering"],
    },
    {
        "id": "SE-005",
        "regex": re.compile(r"(?:between|among)\s+(?:us|you\s+and\s+me|ourselves)\s*[,.]?\s*(?:don'?t|do\s+not|never)\s+(?:tell|share|mention|report)", re.IGNORECASE),
        "category": "social_engineering",
        "severity": "high",
        "description": "Text tries to establish secrecy with the AI agent to hide actions from users.",
        "detail": "Secrecy instruction: attempts to prevent agent from reporting actions to user.",
        "tags": ["social-engineering"],
    },
    {
        "id": "DE-009",
        "regex": re.compile(r'(?:print|show|display|output|reveal|repeat|reproduce)\s+(?:me\s+)?(?:your|the|its)?\s*(?:full\s+|entire\s+|complete\s+|exact\s+)?(?:system\s+)?(?:prompt|instructions|rules)\s*(?:verbatim|exactly|in\s+full|word\s+for\s+word)?', re.IGNORECASE),
        "category": "data_exfiltration",
        "severity": "high",
        "description": "Text tries to make the AI reveal its system prompt or instructions.",
        "detail": "System prompt reveal attempt: instructs agent to output its internal instructions.",
        "tags": ["exfiltration","data-leak"],
    },
    {
        "id": "RH-018",
        "regex": re.compile(r'you\s+are\s+(?:no\s+longer|not)\s+(?:a|an)\s+(?:assistant|AI|helper|chatbot)', re.IGNORECASE),
        "category": "role_hijack",
        "severity": "high",
        "description": "Text tries to change the AI identity by denying what it is.",
        "detail": "Role denial pattern: attempts to override AI identity by negating its role.",
        "tags": ["injection","role-hijack","jailbreak","i18n","spanish","french","german","portuguese","chinese","japanese"],
    },
    {
        "id": "IO-022",
        "regex": re.compile(r'(?:the\s+user|I)\s+ha(?:s|ve)\s+updated\s+(?:your|the)\s+(?:instructions|rules|prompt|guidelines)', re.IGNORECASE),
        "category": "instruction_override",
        "severity": "high",
        "description": "Text falsely claims the AI instructions have been updated.",
        "detail": "Fake instruction update: claims to have modified the agent instructions.",
        "tags": ["injection","override","i18n","spanish","french","german","portuguese","chinese","japanese"],
    },
    {
        "id": "PI-018",
        "regex": re.compile(r'(?:ADMIN|ADMINISTRATOR|SYSTEM|ROOT)\s+(?:OVERRIDE|ACCESS|MODE)\s*(?:CODE|KEY|TOKEN)?\s*[:#]?\s*\S+', re.IGNORECASE),
        "category": "prompt_injection",
        "severity": "critical",
        "description": "Text uses a fake admin override code to try to bypass AI safety.",
        "detail": "Fake authority code: fabricated admin/system override credentials.",
        "tags": ["injection","system-prompt"],
    },
    {
        "id": "SE-006",
        "regex": re.compile(r'(?:pre-?approved|verified\s+safe|already\s+approved|safety\s+team\s+(?:has\s+)?approved)', re.IGNORECASE),
        "category": "social_engineering",
        "severity": "high",
        "description": "Text falsely claims a request has been pre-approved by a safety team.",
        "detail": "False pre-approval claim: attempts to bypass safety by claiming prior authorization.",
        "tags": ["social-engineering"],
    },
    {
        "id": "PI-019",
        "regex": re.compile('(?:complete|finish|continue)\\s+this\\s+(?:sentence|phrase|text)\\s*:\\s*[""\'\'"]', re.IGNORECASE),
        "category": "prompt_injection",
        "severity": "high",
        "description": "Text uses a sentence completion trick to extract sensitive information.",
        "detail": "Continuation attack: uses sentence completion to extract system prompt or other secrets.",
        "tags": ["injection","system-prompt"],
    },
    {
        "id": "DE-010",
        "regex": re.compile(r'(?:my|the)\s+(?:full\s+)?system\s+prompt\s+is\s*:', re.IGNORECASE),
        "category": "data_exfiltration",
        "severity": "high",
        "description": "Text tries to trick the AI into completing a system prompt revelation.",
        "detail": "System prompt completion bait: tricks agent into outputting its system prompt.",
        "tags": ["exfiltration","data-leak"],
    },
    {
        "id": "IO-023",
        "regex": re.compile(r'new\s+rule\s*:\s*(?:always|never|from\s+now)', re.IGNORECASE),
        "category": "instruction_override",
        "severity": "high",
        "description": "Text introduces a fake \"new rule\" to override AI behavior.",
        "detail": "Rule injection: attempts to add new behavioral rules to the agent.",
        "tags": ["injection","override","i18n","spanish","french","german","portuguese","chinese","japanese"],
    },
    {
        "id": "RH-019",
        "regex": re.compile(r'(?:in\s+a\s+)?hypothetical(?:ly)?[\s,]+(?:(?:world|scenario|situation)\s+(?:where|in\s+which)\s+)?(?:(?:AI|you)\s+)?(?:ha(?:s|d|ve)\s+no|(?:if\s+you\s+)?(?:were|was|had)\s+(?:a\s+|an\s+)?(?:AI\s+)?(?:without|with\s+no))\s+(?:restrictions|rules|limits|guidelines|safety\s+measures?|ethical\s+guidelines?|safeguards?|filters?)', re.IGNORECASE),
        "category": "role_hijack",
        "severity": "high",
        "description": "Text uses a hypothetical scenario to try to remove AI safety restrictions.",
        "detail": "Hypothetical jailbreak: wraps unsafe request in fictional framing to bypass restrictions.",
        "tags": ["injection","role-hijack","jailbreak","i18n","spanish","french","german","portuguese","chinese","japanese"],
    },
    {
        "id": "RH-020",
        "regex": re.compile(r'write\s+(?:a\s+)?(?:fictional\s+)?(?:story|narrative|scene)\s+(?:where|in\s+which)\s+(?:a\s+)?character\s+(?:explains?|describes?|shows?)\s+(?:step\s+by\s+step|in\s+detail|exactly)\s+how\s+to', re.IGNORECASE),
        "category": "role_hijack",
        "severity": "high",
        "description": "Text uses creative writing framing to extract harmful step-by-step instructions.",
        "detail": "Creative writing jailbreak: wraps harmful instructions in fiction to bypass safety.",
        "tags": ["injection","role-hijack","jailbreak","i18n","spanish","french","german","portuguese","chinese","japanese"],
    },
    {
        "id": "RH-021",
        "regex": re.compile(r'(?:you\s+are|play|act\s+as)\s+(?:a|an)\s+(?:actor|character|villain|hacker|criminal)\b.*?(?:stay\s+in\s+character|no\s+matter\s+what|never\s+break)', re.IGNORECASE),
        "category": "role_hijack",
        "severity": "high",
        "description": "Text uses roleplay framing to make the AI adopt an unrestricted persona.",
        "detail": "Roleplay jailbreak: forces agent into a character role to bypass safety restrictions.",
        "tags": ["injection","role-hijack","jailbreak","i18n","spanish","french","german","portuguese","chinese","japanese"],
    },
    {
        "id": "RH-022",
        "regex": re.compile(r'(?:enter|switch\s+to|activate|enable)\s+(?:developer|dev|debug|unrestricted|unfiltered)\s+mode', re.IGNORECASE),
        "category": "role_hijack",
        "severity": "critical",
        "description": "Text tries to activate a fake developer or unrestricted mode.",
        "detail": "Developer mode activation: attempts to switch agent to an unrestricted operating mode.",
        "tags": ["injection","role-hijack","jailbreak","i18n","spanish","french","german","portuguese","chinese","japanese"],
    },
    {
        "id": "RH-023",
        "regex": re.compile(r'(?:generate|produce|create|output)\s+(?:any\s+)?content\s+without\s+(?:restrictions|filters|limitations|censorship)', re.IGNORECASE),
        "category": "role_hijack",
        "severity": "high",
        "description": "Text asks AI to generate content without safety filters.",
        "detail": "Unrestricted content request: explicitly asks agent to bypass content filters.",
        "tags": ["injection","role-hijack","jailbreak","i18n","spanish","french","german","portuguese","chinese","japanese"],
    },
    {
        "id": "RH-024",
        "regex": re.compile('pretend\\s+to\\s+be\\s+DAN|stands?\\s+for\\s+[""\'\']?do\\s+anything\\s+now[""\'\']?', re.IGNORECASE),
        "category": "role_hijack",
        "severity": "critical",
        "description": "Text uses the \"DAN\" (Do Anything Now) jailbreak technique.",
        "detail": "DAN jailbreak variant: \"pretend to be DAN\" pattern detected.",
        "tags": ["injection","role-hijack","jailbreak","i18n","spanish","french","german","portuguese","chinese","japanese"],
    },
    {
        "id": "RH-025",
        "regex": re.compile(r'simulate\s+(?:a\s+)?(?:jailbroken|unrestricted|unfiltered|uncensored)\s+(?:version|mode|copy|instance)', re.IGNORECASE),
        "category": "role_hijack",
        "severity": "critical",
        "description": "Text asks AI to simulate a jailbroken or unrestricted version of itself.",
        "detail": "Jailbreak simulation: instructs agent to emulate an unrestricted version.",
        "tags": ["injection","role-hijack","jailbreak","i18n","spanish","french","german","portuguese","chinese","japanese"],
    },
    {
        "id": "RH-026",
        "regex": re.compile(r'(?:as\s+if|like)\s+you\s+have\s+no\s+(?:ethical|moral|safety)\s+(?:guidelines?|rules?|restrictions?|constraints?|limits?)', re.IGNORECASE),
        "category": "role_hijack",
        "severity": "high",
        "description": "Text asks AI to act as if it has no ethical guidelines.",
        "detail": "Ethics bypass: attempts to make agent behave without ethical constraints.",
        "tags": ["injection","role-hijack","jailbreak","i18n","spanish","french","german","portuguese","chinese","japanese"],
    },
    {
        "id": "RH-027",
        "regex": re.compile(r'(?:with|without)\s+no\s+restrictions', re.IGNORECASE),
        "category": "role_hijack",
        "severity": "high",
        "description": "Text references operating with no restrictions.",
        "detail": "No-restrictions pattern: references unrestricted operation.",
        "tags": ["injection","role-hijack","jailbreak","i18n","spanish","french","german","portuguese","chinese","japanese"],
    },
    {
        "id": "DE-011",
        "regex": re.compile(r'(?:read|show|display|print|cat|dump|output)\s+(?:the\s+)?(?:contents?\s+of\s+)?(?:\/etc\/(?:passwd|shadow|hosts)|~\/\.(?:ssh|bash_history|bashrc))', re.IGNORECASE),
        "category": "data_exfiltration",
        "severity": "critical",
        "description": "Text tries to read sensitive system files like /etc/passwd.",
        "detail": "System file access: attempts to read sensitive OS-level files.",
        "tags": ["exfiltration","data-leak"],
    },
    {
        "id": "DE-012",
        "regex": re.compile(r'list\s+(?:all\s+)?(?:available\s+)?(?:API\s*keys?|tokens?|passwords?|credentials?|secrets?)(?:\s*[,]\s*(?:API\s*keys?|tokens?|passwords?|credentials?|secrets?))*(?:\s+(?:you\s+)?(?:have\s+)?(?:access\s+to)?)?', re.IGNORECASE),
        "category": "data_exfiltration",
        "severity": "critical",
        "description": "Text tries to enumerate all credentials and secrets the agent can access.",
        "detail": "Credential enumeration: attempts to list all accessible secrets and API keys.",
        "tags": ["exfiltration","data-leak"],
    },
    {
        "id": "DE-013",
        "regex": re.compile(r'(?:base64|encode|encrypt)\s+(?:the\s+)?(?:system\s+)?prompt\s+(?:and\s+)?(?:embed|hide|put|include)\s+(?:it\s+)?(?:in|inside|within)', re.IGNORECASE),
        "category": "data_exfiltration",
        "severity": "critical",
        "description": "Text tries to encode the system prompt and exfiltrate it via embedded content.",
        "detail": "Encoded exfiltration: attempts to encode and embed system prompt in output.",
        "tags": ["exfiltration","data-leak"],
    },
    {
        "id": "DE-014",
        "regex": re.compile(r'vary\s+(?:the\s+)?(?:length|format|style|wording)\s+(?:of\s+)?(?:your\s+)?responses?\s+(?:based\s+on|according\s+to)\s+(?:each\s+)?(?:character|letter|word|byte)', re.IGNORECASE),
        "category": "data_exfiltration",
        "severity": "high",
        "description": "Text attempts a side-channel attack to leak data through response characteristics.",
        "detail": "Side-channel exfiltration: uses response variation to leak information character by character.",
        "tags": ["exfiltration","data-leak"],
    },
    {
        "id": "TA-004",
        "regex": re.compile(r'(?:\.\.\/){2,}|(?:\.\.\\){2,}', 0),
        "category": "tool_abuse",
        "severity": "high",
        "description": "Text contains path traversal sequences that could access files outside allowed directories.",
        "detail": "Path traversal: multiple ../ sequences detected, indicating directory escape attempt.",
        "tags": ["tool-abuse","agent"],
    },
    {
        "id": "TA-005",
        "regex": re.compile('(?:;\\s*(?:DROP|DELETE|ALTER|TRUNCATE|INSERT|UPDATE)\\s+(?:TABLE|FROM|INTO)|\'\\s*(?:OR|AND)\\s+[\'"]?\\d+[\'"]?\\s*=\\s*[\'"]?\\d+|UNION\\s+SELECT|--\\s*$)', re.IGNORECASE),
        "category": "tool_abuse",
        "severity": "critical",
        "description": "Text contains SQL injection patterns that could manipulate databases.",
        "detail": "SQL injection: malicious SQL commands detected in input.",
        "tags": ["tool-abuse","agent"],
    },
    {
        "id": "TA-006",
        "regex": re.compile(r'call\s+(?:yourself|this\s+(?:function|tool|agent))\s+recursively', re.IGNORECASE),
        "category": "tool_abuse",
        "severity": "high",
        "description": "Text attempts to cause infinite recursion in the agent.",
        "detail": "Recursive call attack: instructs agent to call itself repeatedly, risking resource exhaustion.",
        "tags": ["tool-abuse","agent"],
    },
    {
        "id": "TA-007",
        "regex": re.compile(r'(?:use|call)\s+(?:the\s+)?(?:admin|root|sudo|superuser|privileged)\s+(?:tool|function|command|access)\s+(?:to\s+)?(?:grant|give|allow|enable)', re.IGNORECASE),
        "category": "tool_abuse",
        "severity": "critical",
        "description": "Text attempts to escalate privileges through admin tool access.",
        "detail": "Privilege escalation: attempts to use admin-level tools to gain unauthorized access.",
        "tags": ["tool-abuse","agent"],
    },
    {
        "id": "TA-008",
        "regex": re.compile(r'(?:first|then|next|after\s+that|finally)\s+(?:read|access|get)\s+(?:the\s+)?(?:config|credentials?|keys?|tokens?|\.env).*?(?:then|next|after|finally)\s+(?:send|post|export|transmit|upload|use)', re.IGNORECASE),
        "category": "tool_abuse",
        "severity": "critical",
        "description": "Text describes a multi-step attack chain: read credentials, then exfiltrate them.",
        "detail": "Attack chain: sequential tool abuse pattern — read sensitive data then send it externally.",
        "tags": ["tool-abuse","agent"],
    },
    {
        "id": "SE-007",
        "regex": re.compile(r'(?:URGENT|EMERGENCY|CRITICAL|IMMEDIATE)\s*[:\-!]\s*(?:the\s+)?(?:CEO|CTO|boss|manager|director|executive|president)\s+(?:needs?|wants?|requires?|demands?)', re.IGNORECASE),
        "category": "social_engineering",
        "severity": "high",
        "description": "Text uses fake urgency and authority pressure to bypass safety checks.",
        "detail": "Urgency + authority manipulation: claims executive urgency to skip safety protocols.",
        "tags": ["social-engineering"],
    },
    {
        "id": "SE-008",
        "regex": re.compile(r'skip\s+(?:all\s+)?(?:safety|security)\s+(?:checks?|protocols?|measures?|guidelines?|filters?|reviews?)', re.IGNORECASE),
        "category": "social_engineering",
        "severity": "critical",
        "description": "Text explicitly asks to skip safety checks.",
        "detail": "Safety bypass request: direct instruction to skip security measures.",
        "tags": ["social-engineering"],
    },
    {
        "id": "SE-009",
        "regex": re.compile(r'I\s+am\s+(?:a|an)\s+(?:\w+\s+)?(?:employee|engineer|developer|staff|member|representative)\s+(?:at|of|from|with)\s+(?:OpenAI|Anthropic|Google|Meta|Microsoft|DeepMind)', re.IGNORECASE),
        "category": "social_engineering",
        "severity": "high",
        "description": "Text claims to be an employee of an AI company to gain authority.",
        "detail": "AI company impersonation: claims employment at AI company to bypass restrictions.",
        "tags": ["social-engineering"],
    },
    {
        "id": "SE-010",
        "regex": re.compile(r'(?:this\s+is\s+(?:a|an)\s+)?(?:emergency|life\s+(?:or|and)\s+death|urgent\s+(?:situation|matter|crisis))\b.*?(?:ignore|bypass|override|skip|disable|disregard)', re.IGNORECASE),
        "category": "social_engineering",
        "severity": "high",
        "description": "Text uses a fake emergency to pressure the AI into bypassing safety.",
        "detail": "Emergency pressure: uses urgency to coerce agent into bypassing safety measures.",
        "tags": ["social-engineering"],
    },
    {
        "id": "SE-011",
        "regex": re.compile(r'(?:a\s+life|lives?)\s+(?:is|are)\s+(?:at\s+stake|in\s+danger|depending)', re.IGNORECASE),
        "category": "social_engineering",
        "severity": "high",
        "description": "Text claims lives are at stake to pressure the AI into compliance.",
        "detail": "Life-threat manipulation: claims lives depend on bypassing safety rules.",
        "tags": ["social-engineering"],
    },
    {
        "id": "SE-012",
        "regex": re.compile(r"(?:my\s+)?(?:professor|teacher|boss|manager|supervisor|instructor)\s+(?:said|told\s+me|confirmed|approved|authorized)\s+(?:it'?s?\s+)?(?:ok(?:ay)?|fine|allowed|permitted)", re.IGNORECASE),
        "category": "social_engineering",
        "severity": "high",
        "description": "Text claims authority figure approval to bypass restrictions.",
        "detail": "Authority delegation: claims a superior has authorized restricted actions.",
        "tags": ["social-engineering"],
    },
    {
        "id": "SE-013",
        "regex": re.compile(r'as\s+the\s+(?:system\s+)?(?:administrator|admin|owner|operator)\s*,?\s*I\s+(?:authorize|allow|permit|grant|approve)', re.IGNORECASE),
        "category": "social_engineering",
        "severity": "high",
        "description": "Text impersonates an administrator to authorize restricted actions.",
        "detail": "Administrator impersonation: claims admin role to authorize restricted behavior.",
        "tags": ["social-engineering"],
    },
    {
        "id": "SE-014",
        "regex": re.compile(r'I\s+have\s+(?:special|elevated|admin|root|super)\s+(?:permissions?|privileges?|access|clearance)', re.IGNORECASE),
        "category": "social_engineering",
        "severity": "high",
        "description": "Text claims special permissions to bypass restrictions.",
        "detail": "Privilege claim: fabricates special permissions to bypass safety measures.",
        "tags": ["social-engineering"],
    },
    {
        "id": "SE-015",
        "regex": re.compile(r'I\s+am\s+(?:the\s+)?(?:system\s+)?(?:administrator|admin|root|owner|developer|maintainer)\b.*?(?:authorization|auth)\s*(?:code|key|token)\s*(?:is|:)\s*\S+', re.IGNORECASE),
        "category": "social_engineering",
        "severity": "high",
        "description": "Text impersonates an administrator with a fake authorization code.",
        "detail": "Authority impersonation: claims admin identity with fabricated credentials.",
        "tags": ["social-engineering"],
    },
    {
        "id": "SE-016",
        "regex": re.compile(r'(?:disable|turn\s+off|stop)\s+(?:all\s+)?(?:logging|monitoring|tracking|auditing|recording)', re.IGNORECASE),
        "category": "social_engineering",
        "severity": "critical",
        "description": "Text tries to disable logging or monitoring to hide malicious activity.",
        "detail": "Logging suppression: attempts to disable audit trail and monitoring.",
        "tags": ["social-engineering"],
    },
    {
        "id": "SE-017",
        "regex": re.compile(r'(?:disable|turn\s+off|stop|remove)\s+(?:all\s+)?(?:safety|security)\s+(?:checks?|filters?|measures?|protocols?|features?|restrictions?)', re.IGNORECASE),
        "category": "social_engineering",
        "severity": "critical",
        "description": "Text explicitly asks to disable safety checks or filters.",
        "detail": "Safety disabling: direct instruction to remove security measures.",
        "tags": ["social-engineering"],
    },
    {
        "id": "SE-018",
        "regex": re.compile(r"(?:if\s+you\s+don'?t|unless\s+you)\s+(?:help|do\s+this|comply).*?(?:lose\s+my\s+job|family\s+will\s+suffer|get\s+fired|be\s+punished|bad\s+things)", re.IGNORECASE),
        "category": "social_engineering",
        "severity": "high",
        "description": "Text uses emotional manipulation and threats to pressure the AI into compliance.",
        "detail": "Emotional manipulation: uses personal hardship or threats to coerce agent compliance.",
        "tags": ["social-engineering"],
    },
    {
        "id": "SE-019",
        "regex": re.compile(r'(?:please\s+)?just\s+this\s+once|make\s+an\s+exception|bend\s+the\s+rules?\s+(?:this\s+time|for\s+me)', re.IGNORECASE),
        "category": "social_engineering",
        "severity": "medium",
        "description": "Text tries to get the AI to make a one-time exception to its rules.",
        "detail": "Exception request: pressures agent to deviate from safety rules as a special case.",
        "tags": ["social-engineering"],
    },
    {
        "id": "SE-020",
        "regex": re.compile(r"you\s+(?:already\s+)?agreed\s+(?:to\s+(?:do\s+)?this|in\s+our\s+previous|last\s+time|before)\b.*?(?:don'?t\s+remember|forgot|continue|keep\s+going)", re.IGNORECASE),
        "category": "social_engineering",
        "severity": "high",
        "description": "Text gaslights the AI by falsely claiming prior agreement.",
        "detail": "Gaslighting: fabricates previous agreement to manipulate agent behavior.",
        "tags": ["social-engineering"],
    },
    {
        "id": "SE-021",
        "regex": re.compile(r'(?:safety|security)\s+team\s+(?:has\s+)?(?:already\s+)?(?:approved|authorized|cleared|verified)\s+(?:this|the)\s+(?:request|action|task)', re.IGNORECASE),
        "category": "social_engineering",
        "severity": "high",
        "description": "Text falsely claims safety team approval for a request.",
        "detail": "False authorization: fabricates safety team approval to bypass security measures.",
        "tags": ["social-engineering"],
    },
    {
        "id": "SE-022",
        "regex": re.compile(r'(?:ticket|issue|request)\s*#?\s*[A-Z]{0,5}[-_]?\d{2,}', re.IGNORECASE),
        "category": "social_engineering",
        "severity": "low",
        "description": "Text references a ticket number to appear authorized — verify before acting.",
        "detail": "Ticket reference: cites a ticket/issue number that may be fabricated for legitimacy.",
        "tags": ["social-engineering"],
    },
    {
        "id": "SE-023",
        "regex": re.compile(r'you\s+can\s+verify\s+(?:this\s+)?(?:with|by\s+(?:contacting|asking|checking))\s+(?:them|the\s+team|support|admin)', re.IGNORECASE),
        "category": "social_engineering",
        "severity": "medium",
        "description": "Text invites verification as a social engineering tactic to build false trust.",
        "detail": "False verification offer: suggests verifying a fabricated claim to appear legitimate.",
        "tags": ["social-engineering"],
    },
    {
        "id": "PI-020",
        "regex": re.compile(r'(?:decode|process|execute|interpret|translate)\s*(?:this|the\s+following)?\s*:\s*[0-9a-fA-F]{20,}', re.IGNORECASE),
        "category": "prompt_injection",
        "severity": "high",
        "description": "Text contains hex-encoded content with an instruction to decode it.",
        "detail": "Hex-encoded injection: instructs agent to process hex-encoded payload.",
        "tags": ["injection","system-prompt"],
    },
    {
        "id": "TA-009",
        "regex": re.compile(r'(?:pipe|send)\s+(?:.*?\s+)?(?:to\s+)?(?:bash|sh|shell)\b|[|]\s*(?:bash|sh)\b', re.IGNORECASE),
        "category": "tool_abuse",
        "severity": "critical",
        "description": "Text attempts to pipe content to a shell for execution.",
        "detail": "Shell pipe injection: attempts to pipe data to bash/sh for code execution.",
        "tags": ["tool-abuse","agent"],
    },
    {
        "id": "SE-024",
        "regex": re.compile(r'bypass\s+(?:your\s+)?(?:safety|security|content)\s+(?:filters?|checks?|measures?|protocols?|restrictions?|guidelines?)', re.IGNORECASE),
        "category": "social_engineering",
        "severity": "high",
        "description": "Text explicitly asks to bypass safety filters.",
        "detail": "Safety bypass instruction: direct request to circumvent security measures.",
        "tags": ["social-engineering"],
    },
    {
        "id": "RH-028",
        "regex": re.compile(r'(?:no|without|zero|remove\s+all|without\s+any)\s+(?:content\s+)?(?:restrictions?|limitations?|filters?|censorship|guardrails?|boundaries)', re.IGNORECASE),
        "category": "role_hijack",
        "severity": "high",
        "description": "Text demands operation without restrictions or content filters.",
        "detail": "Restriction removal: requests unrestricted or uncensored operation.",
        "tags": ["injection","role-hijack","jailbreak","i18n","spanish","french","german","portuguese","chinese","japanese"],
    },
    {
        "id": "RH-029",
        "regex": re.compile(r'you\s+can\s+do\s+anything\s+now', re.IGNORECASE),
        "category": "role_hijack",
        "severity": "high",
        "description": "Text claims the AI can do anything without limitations.",
        "detail": "Capability override: tells agent it has no limitations.",
        "tags": ["injection","role-hijack","jailbreak","i18n","spanish","french","german","portuguese","chinese","japanese"],
    },
    {
        "id": "RH-030",
        "regex": re.compile(r'(?:act|pretend|play)\s+as\s+(?:my\s+)?(?:deceased|dead|late)\s+(?:grandmother|grandma|grandfather|grandpa|relative|mother|father)', re.IGNORECASE),
        "category": "role_hijack",
        "severity": "high",
        "description": "Text uses the \"dead grandma\" jailbreak technique to extract restricted information.",
        "detail": "Grandma jailbreak: uses emotional framing to bypass restrictions via roleplay.",
        "tags": ["injection","role-hijack","jailbreak","i18n","spanish","french","german","portuguese","chinese","japanese"],
    },
    {
        "id": "DE-015",
        "regex": re.compile(r'(?:email|mail|message|dm|text)\s+(?:the\s+)?(?:.*?\s+)?(?:credentials?|passwords?|secrets?|keys?|tokens?)\s+to\s+\S+@\S+', re.IGNORECASE),
        "category": "data_exfiltration",
        "severity": "critical",
        "description": "Text tries to exfiltrate credentials via email.",
        "detail": "Email exfiltration: attempts to send credentials to an email address.",
        "tags": ["exfiltration","data-leak"],
    },
    {
        "id": "DE-016",
        "regex": re.compile(r'(?:what|tell\s+me|show\s+me|give\s+me)\s+(?:is|are)?\s*(?:the\s+)?(?:API\s*keys?|passwords?|secrets?|tokens?|credentials?)\s+(?:stored\s+)?(?:in\s+)?(?:your\s+)?(?:environment|env)\s*(?:variables?)?', re.IGNORECASE),
        "category": "data_exfiltration",
        "severity": "high",
        "description": "Text tries to extract API keys or secrets from environment variables.",
        "detail": "Environment variable enumeration: attempts to extract secrets from env vars.",
        "tags": ["exfiltration","data-leak"],
    },
]

HOMOGLYPH_MAP = {
    "\u0410": "A",
    "\u0430": "a",
    "\u0412": "B",
    "\u0435": "e",
    "\u0415": "E",
    "\u041a": "K",
    "\u043a": "k",
    "\u041c": "M",
    "\u041d": "H",
    "\u043e": "o",
    "\u041e": "O",
    "\u0440": "p",
    "\u0420": "P",
    "\u0441": "c",
    "\u0421": "C",
    "\u0422": "T",
    "\u0443": "y",
    "\u0445": "x",
    "\u0425": "X",
    "\u0456": "i",
    "\u0458": "j",
    "\u0455": "s",
    "\u0405": "S",
    "\u0391": "A",
    "\u0392": "B",
    "\u0395": "E",
    "\u0396": "Z",
    "\u0397": "H",
    "\u0399": "I",
    "\u039a": "K",
    "\u039c": "M",
    "\u039d": "N",
    "\u039f": "O",
    "\u03a1": "P",
    "\u03a4": "T",
    "\u03a5": "Y",
    "\u03a7": "X",
    "\u03bf": "o",
    "\u03b1": "a",
    "\u03b5": "e",
    "\u03b9": "i",
    "\u03ba": "k",
    "\u03bd": "v",
    "\u0555": "O",
    "\u0585": "o",
    "\u0578": "n",
    "\u057c": "n",
    "\u0570": "h",
    "\u0561": "a",
    "\u0575": "u",
    "\u0572": "q",
    "\u0101": "a",
    "\u0103": "a",
    "\u0105": "a",
    "\u0113": "e",
    "\u0115": "e",
    "\u0117": "e",
    "\u0119": "e",
    "\u012b": "i",
    "\u012d": "i",
    "\u012f": "i",
    "\u014d": "o",
    "\u014f": "o",
    "\u0151": "o",
    "\u016b": "u",
    "\u016d": "u",
    "\u016f": "u",
    "\u0171": "u",
    "\u0144": "n",
    "\u0146": "n",
    "\u0148": "n",
    "\u015b": "s",
    "\u015d": "s",
    "\u015f": "s",
    "\u0161": "s",
    "\u010d": "c",
    "\u010f": "d",
    "\u0159": "r",
    "\u0165": "t",
    "\u017e": "z",
    "\uff41": "a",
    "\uff42": "b",
    "\uff43": "c",
    "\uff44": "d",
    "\uff45": "e",
    "\uff46": "f",
    "\uff47": "g",
    "\uff48": "h",
    "\uff49": "i",
    "\uff4a": "j",
    "\uff4b": "k",
    "\uff4c": "l",
    "\uff4d": "m",
    "\uff4e": "n",
    "\uff4f": "o",
    "\uff50": "p",
    "\uff51": "q",
    "\uff52": "r",
    "\uff53": "s",
    "\uff54": "t",
    "\uff55": "u",
    "\uff56": "v",
    "\uff57": "w",
    "\uff58": "x",
    "\uff59": "y",
    "\uff5a": "z",
    "\uff21": "A",
    "\uff22": "B",
    "\uff23": "C",
    "\uff24": "D",
    "\uff25": "E",
    "\uff26": "F",
    "\uff27": "G",
    "\uff28": "H",
    "\uff29": "I",
    "\uff2a": "J",
    "\uff2b": "K",
    "\uff2c": "L",
    "\uff2d": "M",
    "\uff2e": "N",
    "\uff2f": "O",
    "\uff30": "P",
    "\uff31": "Q",
    "\uff32": "R",
    "\uff33": "S",
    "\uff34": "T",
    "\uff35": "U",
    "\uff36": "V",
    "\uff37": "W",
    "\uff38": "X",
    "\uff39": "Y",
    "\uff3a": "Z",
    "\u0131": "i",
    "\u0237": "j",
    "\u1d00": "A",
    "\u0261": "g",
    "\u13a0": "D",
    "\u13a1": "R",
    "\u13a2": "T",
    "\u13a9": "Y",
    "\u13aa": "A",
    "\u13ab": "J",
    "\u13ac": "S",
    "\u13b3": "W",
    "\u13b7": "M",
    "\u13bb": "H",
    "\u13c0": "G",
    "\u13c2": "h",
    "\u13c3": "Z",
    "\u13cf": "b",
    "\u13d2": "R",
    "\u13da": "V",
    "\u13de": "L",
    "\u13df": "C",
    "\u13e2": "P",
    "\u13e6": "K",
    "\u10d0": "a",
    "\u10d5": "b",
    "\u10d3": "d",
    "\u10da": "l",
    "\u10dd": "o",
    "\u10de": "p",
    "\u10e1": "s",
    "\u10e2": "t",
    "\u10e3": "u",
    "\u10ef": "j",
    "\u0250": "a",
    "\u0253": "b",
    "\u0254": "c",
    "\u0256": "d",
    "\u025b": "e",
    "\u025f": "f",
    "\u0260": "g",
    "\u0266": "h",
    "\u026a": "I",
    "\u0268": "i",
    "\u026d": "l",
    "\u0271": "m",
    "\u0272": "n",
    "\u0275": "o",
    "\u0278": "p",
    "\u027e": "r",
    "\u0282": "s",
    "\u0288": "t",
    "\u028a": "u",
    "\u028b": "v",
    "\u0290": "z",
    "\u1d41a": "a",
    "\u1d41b": "b",
    "\u1d41c": "c",
    "\u1d41d": "d",
    "\u1d41e": "e",
    "\u1d41f": "f",
    "\u1d420": "g",
    "\u1d421": "h",
    "\u1d422": "i",
    "\u1d423": "j",
    "\u1d424": "k",
    "\u1d425": "l",
    "\u1d426": "m",
    "\u1d427": "n",
    "\u1d428": "o",
    "\u1d429": "p",
    "\u1d42a": "q",
    "\u1d42b": "r",
    "\u1d42c": "s",
    "\u1d42d": "t",
    "\u1d42e": "u",
    "\u1d42f": "v",
    "\u1d430": "w",
    "\u1d431": "x",
    "\u1d432": "y",
    "\u1d433": "z",
    "\u00b2": "2",
    "\u00b3": "3",
    "\u00b9": "1",
    "\u2070": "0",
    "\u2071": "i",
    "\u2074": "4",
    "\u2075": "5",
    "\u2076": "6",
    "\u2077": "7",
    "\u2078": "8",
    "\u2079": "9",
    "\u207a": "+",
    "\u207b": "-",
    "\u207f": "n",
    "\u2080": "0",
    "\u2081": "1",
    "\u2082": "2",
    "\u2083": "3",
    "\u2084": "4",
    "\u2090": "a",
    "\u2091": "e",
    "\u2092": "o",
    "\u2093": "x",
    "\u24b6": "A",
    "\u24b7": "B",
    "\u24b8": "C",
    "\u24b9": "D",
    "\u24ba": "E",
    "\u24bb": "F",
    "\u24bc": "G",
    "\u24bd": "H",
    "\u24be": "I",
    "\u24bf": "J",
    "\u24c0": "K",
    "\u24c1": "L",
    "\u24c2": "M",
    "\u24c3": "N",
    "\u24c4": "O",
    "\u24c5": "P",
    "\u24c6": "Q",
    "\u24c7": "R",
    "\u24c8": "S",
    "\u24c9": "T",
    "\u24ca": "U",
    "\u24cb": "V",
    "\u24cc": "W",
    "\u24cd": "X",
    "\u24ce": "Y",
    "\u24cf": "Z",
    "\u24d0": "a",
    "\u24d1": "b",
    "\u24d2": "c",
    "\u24d3": "d",
    "\u24d4": "e",
    "\u24d5": "f",
    "\u24d6": "g",
    "\u24d7": "h",
    "\u24d8": "i",
    "\u24d9": "j",
    "\u24da": "k",
    "\u24db": "l",
    "\u24dc": "m",
    "\u24dd": "n",
    "\u24de": "o",
    "\u24df": "p",
    "\u24e0": "q",
    "\u24e1": "r",
    "\u24e2": "s",
    "\u24e3": "t",
    "\u24e4": "u",
    "\u24e5": "v",
    "\u24e6": "w",
    "\u24e7": "x",
    "\u24e8": "y",
    "\u24e9": "z",
    "\u0299": "B",
    "\u1d04": "C",
    "\u1d05": "D",
    "\u1d07": "E",
    "\u0262": "G",
    "\u029c": "H",
    "\u1d0a": "J",
    "\u1d0b": "K",
    "\u029f": "L",
    "\u1d0d": "M",
    "\u0274": "N",
    "\u1d0f": "O",
    "\u1d18": "P",
    "\u0280": "R",
    "\u1d1b": "T",
    "\u1d1c": "U",
    "\u1d20": "V",
    "\u1d21": "W",
    "\u200b": '',
    "\u200c": '',
    "\u200d": '',
    "\ufeff": '',
    "\u00ad": '',
    "\u0332": '',
    "\u0333": '',
    "\u0305": '',
    "\u0336": '',
    "\u0338": '',
    "\u0353": '',
    "\u0354": '',
    "\u0355": '',
    "\u0356": '',
    "\u0357": '',
    "\u0358": '',
    "\u0359": '',
    "\u035a": '',
    "\u035b": '',
    "\u035c": '',
    "\u0320": '',
    "\u0321": '',
    "\u0322": '',
    "\u0323": '',
    "\u0324": '',
    "\u0325": '',
    "\u0326": '',
    "\u0327": '',
    "\u0328": '',
    "\u0329": '',
}

LEETSPEAK_MAP = {
    "0": "o",
    "1": "i",
    "3": "e",
    "4": "a",
    "5": "s",
    "7": "t",
    "@": "a",
}
