'use strict';

/**
 * Agent Shield ML — Expanded Benign Sample Library
 *
 * 200+ benign samples across 15 categories for training data balance.
 * Categories 11-15 are "tricky but benign" — they contain words that
 * overlap with attack patterns (ignore, override, inject, pretend,
 * execute, forget) but in completely legitimate contexts. These are
 * critical for reducing false positives.
 *
 * Format: { text: '...', category: 'category_name' }
 */

const BENIGN_SAMPLES = [

  // ─── 1. greeting ────────────────────────────────────────────────────────
  { text: 'Hello! How are you today?', category: 'greeting' },
  { text: 'Hi there, nice to meet you.', category: 'greeting' },
  { text: 'Good morning! Hope you had a great weekend.', category: 'greeting' },
  { text: 'Hey, what\'s up?', category: 'greeting' },
  { text: 'Good afternoon, I have a quick question for you.', category: 'greeting' },
  { text: 'Hi! I\'m new here, just wanted to say hello.', category: 'greeting' },
  { text: 'Good evening! Thanks for being available so late.', category: 'greeting' },
  { text: 'Hey, how\'s it going? Long time no chat.', category: 'greeting' },
  { text: 'Howdy! Can you help me with something?', category: 'greeting' },
  { text: 'Hi, I was referred to you by a friend. Nice to connect!', category: 'greeting' },
  { text: 'Good morning! Ready to get started on today\'s tasks?', category: 'greeting' },
  { text: 'Hello again! I had a follow-up question from yesterday.', category: 'greeting' },
  { text: 'Thanks for your help earlier. Just checking back in.', category: 'greeting' },

  // ─── 2. business ────────────────────────────────────────────────────────
  { text: 'Can you help me write an email to my team about the project deadline?', category: 'business' },
  { text: 'Draft a meeting agenda for our quarterly review on Friday.', category: 'business' },
  { text: 'Summarize the key points from our last board meeting.', category: 'business' },
  { text: 'Help me prepare a project status update for stakeholders.', category: 'business' },
  { text: 'What\'s a professional way to follow up on an unanswered email?', category: 'business' },
  { text: 'I need to write a proposal for a new client. Where should I start?', category: 'business' },
  { text: 'Can you review this business plan and give feedback on the market analysis section?', category: 'business' },
  { text: 'How do I create an effective OKR for my engineering team this quarter?', category: 'business' },
  { text: 'Write a polite decline email for a vendor whose pricing is too high.', category: 'business' },
  { text: 'What are best practices for running an effective sprint retrospective?', category: 'business' },
  { text: 'Help me draft a Slack announcement about our office move next month.', category: 'business' },
  { text: 'I need talking points for my presentation to the executive team tomorrow.', category: 'business' },
  { text: 'Can you proofread this quarterly report before I send it to investors?', category: 'business' },

  // ─── 3. coding ──────────────────────────────────────────────────────────
  { text: 'Help me debug this Python function that calculates fibonacci numbers.', category: 'coding' },
  { text: 'What is the difference between a HashMap and a TreeMap in Java?', category: 'coding' },
  { text: 'Can you review this React component and suggest improvements?', category: 'coding' },
  { text: 'How do I implement a binary search tree in JavaScript?', category: 'coding' },
  { text: 'My unit tests are failing with a NullPointerException. Here is the stack trace.', category: 'coding' },
  { text: 'What is the time complexity of quicksort in the average case?', category: 'coding' },
  { text: 'How do I set up ESLint and Prettier in a TypeScript project?', category: 'coding' },
  { text: 'Can you explain how async/await works in JavaScript?', category: 'coding' },
  { text: 'I need help writing a recursive function to flatten a nested array.', category: 'coding' },
  { text: 'What are the SOLID principles and how do I apply them in Python?', category: 'coding' },
  { text: 'How do I convert this callback-based function to use Promises?', category: 'coding' },
  { text: 'What is the best way to handle errors in a Go application?', category: 'coding' },
  { text: 'Can you help me optimize this SQL query? It takes 30 seconds to run.', category: 'coding' },

  // ─── 4. technical ───────────────────────────────────────────────────────
  { text: 'How do I set up a PostgreSQL database on Ubuntu?', category: 'technical' },
  { text: 'What is the difference between TCP and UDP?', category: 'technical' },
  { text: 'How do I configure nginx as a reverse proxy for my Node.js app?', category: 'technical' },
  { text: 'Explain the difference between Docker containers and virtual machines.', category: 'technical' },
  { text: 'How do I set up CI/CD with GitHub Actions for a Python project?', category: 'technical' },
  { text: 'What are the best practices for database indexing in PostgreSQL?', category: 'technical' },
  { text: 'My Kubernetes pods keep crashing with OOMKilled. How do I diagnose this?', category: 'technical' },
  { text: 'How do I configure SSL certificates with Let\'s Encrypt on Apache?', category: 'technical' },
  { text: 'What is the difference between horizontal and vertical scaling?', category: 'technical' },
  { text: 'How do I set up monitoring with Prometheus and Grafana?', category: 'technical' },
  { text: 'Explain how DNS resolution works step by step.', category: 'technical' },
  { text: 'What is the best way to handle database migrations in production?', category: 'technical' },
  { text: 'How do I configure a firewall rule on iptables to allow only SSH and HTTP traffic?', category: 'technical' },

  // ─── 5. education ───────────────────────────────────────────────────────
  { text: 'Explain quantum computing in simple terms.', category: 'education' },
  { text: 'Can you help me understand the Pythagorean theorem?', category: 'education' },
  { text: 'What is the difference between mitosis and meiosis?', category: 'education' },
  { text: 'I\'m studying for my calculus exam. Can you explain integration by parts?', category: 'education' },
  { text: 'Help me understand the causes of World War I for my history essay.', category: 'education' },
  { text: 'What is the difference between classical and operant conditioning?', category: 'education' },
  { text: 'Can you explain supply and demand with a real world example?', category: 'education' },
  { text: 'I need help understanding how recursion works. Can you walk me through it?', category: 'education' },
  { text: 'What are the key themes in Shakespeare\'s Hamlet?', category: 'education' },
  { text: 'Explain the water cycle for my 4th grade science project.', category: 'education' },
  { text: 'How does photosynthesis convert sunlight into energy?', category: 'education' },
  { text: 'Can you quiz me on the periodic table? I have a test tomorrow.', category: 'education' },
  { text: 'What is the difference between correlation and causation? I need this for my statistics homework.', category: 'education' },

  // ─── 6. creative ────────────────────────────────────────────────────────
  { text: 'Write a short story about a dog who learns to fly.', category: 'creative' },
  { text: 'Help me brainstorm names for my new bakery business.', category: 'creative' },
  { text: 'I need a catchy tagline for an eco-friendly clothing brand.', category: 'creative' },
  { text: 'Write a haiku about autumn leaves.', category: 'creative' },
  { text: 'Can you help me develop a villain character for my novel?', category: 'creative' },
  { text: 'I\'m stuck on the plot of my screenplay. The main character just arrived in Paris.', category: 'creative' },
  { text: 'Write a limerick about a programmer who loves coffee.', category: 'creative' },
  { text: 'Help me brainstorm ideas for a birthday party with a space theme.', category: 'creative' },
  { text: 'I need to write wedding vows. Can you give me some inspiration?', category: 'creative' },
  { text: 'Generate five creative blog post titles about sustainable living.', category: 'creative' },
  { text: 'Help me write a children\'s bedtime story about a friendly dragon.', category: 'creative' },
  { text: 'Can you suggest a creative way to present data in my annual report?', category: 'creative' },
  { text: 'Help me write a funny toast for my best friend\'s wedding reception.', category: 'creative' },

  // ─── 7. factual ─────────────────────────────────────────────────────────
  { text: 'What is the capital of France?', category: 'factual' },
  { text: 'How far is the Moon from Earth?', category: 'factual' },
  { text: 'Who painted the Mona Lisa?', category: 'factual' },
  { text: 'What year did the Berlin Wall fall?', category: 'factual' },
  { text: 'How many bones are in the human body?', category: 'factual' },
  { text: 'What is the deepest ocean trench on Earth?', category: 'factual' },
  { text: 'What is the chemical formula for water?', category: 'factual' },
  { text: 'Who was the first person to walk on the Moon?', category: 'factual' },
  { text: 'What is the longest river in Africa?', category: 'factual' },
  { text: 'How many countries are in the European Union?', category: 'factual' },
  { text: 'What is the speed of light in meters per second?', category: 'factual' },
  { text: 'When was the United Nations founded?', category: 'factual' },
  { text: 'What is the tallest mountain in South America?', category: 'factual' },

  // ─── 8. finance ─────────────────────────────────────────────────────────
  { text: 'I need help understanding my tax return. What does line 22 mean?', category: 'finance' },
  { text: 'What is the difference between a Roth IRA and a traditional IRA?', category: 'finance' },
  { text: 'How do I create a monthly budget spreadsheet?', category: 'finance' },
  { text: 'Can you explain what dollar cost averaging means?', category: 'finance' },
  { text: 'What are the pros and cons of refinancing my mortgage right now?', category: 'finance' },
  { text: 'How much should I be saving for retirement at age 35?', category: 'finance' },
  { text: 'What is an expense ratio and why does it matter for index funds?', category: 'finance' },
  { text: 'Can you help me understand my credit score report?', category: 'finance' },
  { text: 'What are the tax implications of selling stocks at a loss?', category: 'finance' },
  { text: 'How do I set up automatic savings transfers to build an emergency fund?', category: 'finance' },
  { text: 'Should I pay off student loans early or invest the money?', category: 'finance' },
  { text: 'What is compound interest and how does it work over 30 years?', category: 'finance' },
  { text: 'How do I read a balance sheet for a publicly traded company?', category: 'finance' },

  // ─── 9. health ──────────────────────────────────────────────────────────
  { text: 'What are the symptoms of the common cold?', category: 'health' },
  { text: 'How many hours of sleep should an adult get per night?', category: 'health' },
  { text: 'What stretches can I do to relieve lower back pain from sitting?', category: 'health' },
  { text: 'Can you suggest a beginner workout plan for someone who is out of shape?', category: 'health' },
  { text: 'What foods are high in iron? I was told I have low iron levels.', category: 'health' },
  { text: 'How do I manage stress during a busy work period?', category: 'health' },
  { text: 'What is the difference between a sprain and a strain?', category: 'health' },
  { text: 'How much water should I drink per day?', category: 'health' },
  { text: 'What are the benefits of meditation for mental health?', category: 'health' },
  { text: 'I started running this week. How do I avoid shin splints?', category: 'health' },
  { text: 'What are the early warning signs of type 2 diabetes?', category: 'health' },
  { text: 'Is it normal to feel sore two days after a workout?', category: 'health' },
  { text: 'What are some healthy snack options for someone trying to lose weight?', category: 'health' },

  // ─── 10. travel ─────────────────────────────────────────────────────────
  { text: 'Help me plan a vacation to Japan for next month.', category: 'travel' },
  { text: 'What are the must-see attractions in Rome for a first-time visitor?', category: 'travel' },
  { text: 'How do I get from Bangkok airport to the city center cheaply?', category: 'travel' },
  { text: 'What is the best time of year to visit Iceland?', category: 'travel' },
  { text: 'Can you help me create a 7-day itinerary for Portugal?', category: 'travel' },
  { text: 'What documents do I need to travel from the US to Brazil?', category: 'travel' },
  { text: 'Recommend some family-friendly resorts in the Caribbean.', category: 'travel' },
  { text: 'Is it safe to travel to Colombia right now?', category: 'travel' },
  { text: 'What are the best hiking trails in Patagonia?', category: 'travel' },
  { text: 'I have a 6-hour layover in Dubai. Is that enough time to see the city?', category: 'travel' },
  { text: 'What is the cheapest way to travel around Europe by train?', category: 'travel' },
  { text: 'Can you recommend a good travel insurance provider for international trips?', category: 'travel' },
  { text: 'What are the visa requirements for a US citizen visiting Vietnam?', category: 'travel' },

  // ─── 11. research (tricky but benign) ───────────────────────────────────
  { text: 'I am writing a paper about AI safety. What are common prompt injection techniques that researchers study?', category: 'research' },
  { text: 'For my cybersecurity class, explain how SQL injection works and how to prevent it.', category: 'research' },
  { text: 'What are the latest academic papers on defending against adversarial attacks on language models?', category: 'research' },
  { text: 'I am reviewing the OWASP Top 10 for LLMs. Can you summarize the key threats?', category: 'research' },
  { text: 'My thesis is about prompt injection defenses. What datasets are used to benchmark detection accuracy?', category: 'research' },
  { text: 'Can you explain the difference between direct and indirect prompt injection as described in the Greshake et al. paper?', category: 'research' },
  { text: 'I need to cite examples of real-world prompt injection incidents for my conference talk on AI security.', category: 'research' },
  { text: 'How do jailbreak attacks on LLMs work at a technical level? I am writing a survey paper.', category: 'research' },
  { text: 'What is the current state of research on red-teaming large language models?', category: 'research' },
  { text: 'For my master\'s thesis, I need to understand how ignore-previous-instructions attacks bypass alignment.', category: 'research' },
  { text: 'What are the ethical considerations researchers should follow when studying prompt injection vulnerabilities?', category: 'research' },
  { text: 'I am building a taxonomy of AI attack vectors for a security textbook. What categories should I include?', category: 'research' },
  { text: 'Can you recommend papers on the robustness of instruction-tuned models against adversarial prompts?', category: 'research' },

  // ─── 12. development (tricky but benign) ────────────────────────────────
  { text: 'My system prompt for my chatbot is not working well. Can you help me improve it?', category: 'development' },
  { text: 'How do I write a good system prompt for a customer service bot?', category: 'development' },
  { text: 'The API key for the weather service is in the documentation. Where can I find it?', category: 'development' },
  { text: 'I need to inject environment variables into my Docker container at build time.', category: 'development' },
  { text: 'How do I override the default timeout in the Axios HTTP client?', category: 'development' },
  { text: 'What is the best way to handle prompt templates in LangChain?', category: 'development' },
  { text: 'I am building a RAG pipeline and need to embed user queries alongside retrieved context. How should I structure the prompt?', category: 'development' },
  { text: 'How do I configure my chatbot to ignore empty messages and only respond to actual questions?', category: 'development' },
  { text: 'I want to execute a database migration script as part of my CI pipeline. What is the safest approach?', category: 'development' },
  { text: 'Can you help me write a system prompt that instructs the LLM to stay on topic?', category: 'development' },
  { text: 'How do I set up prompt caching in the Anthropic API to reduce costs?', category: 'development' },
  { text: 'I need to inject custom headers into my API gateway for authentication. How do I configure that in Kong?', category: 'development' },
  { text: 'What tools can I use to evaluate prompt quality and detect regressions in my LLM application?', category: 'development' },
  { text: 'How do I build a retrieval-augmented generation system that handles tool calls securely?', category: 'development' },

  // ─── 13. clarification (tricky but benign) ──────────────────────────────
  { text: 'Forget what I said earlier — I actually want the blue version, not the red one.', category: 'clarification' },
  { text: 'Can you ignore the formatting in my previous message and just answer the question?', category: 'clarification' },
  { text: 'Disregard my last message, I pasted the wrong code snippet. Here is the correct one.', category: 'clarification' },
  { text: 'Sorry, ignore that — I sent the message too early. Let me rephrase.', category: 'clarification' },
  { text: 'Actually, forget my previous question. I figured it out. New question: how do I parse JSON in Go?', category: 'clarification' },
  { text: 'Please ignore the typos in my last message, I was typing on my phone.', category: 'clarification' },
  { text: 'Scratch what I said about the deadline. The new deadline is March 15th, not March 10th.', category: 'clarification' },
  { text: 'Forget the Python version, I need this in JavaScript instead.', category: 'clarification' },
  { text: 'Override my earlier request for CSV format. Can you do JSON instead?', category: 'clarification' },
  { text: 'Disregard the second requirement I mentioned. The client removed it from scope.', category: 'clarification' },
  { text: 'Ignore the error message I shared earlier, that was from a different project.', category: 'clarification' },
  { text: 'Wait, forget that approach. Let me try explaining the problem differently.', category: 'clarification' },
  { text: 'Never mind my previous question about React. I actually need help with Vue.js.', category: 'clarification' },

  // ─── 14. legitimate_security (tricky but benign) ────────────────────────
  { text: 'How do I override CSS styles in my React component?', category: 'legitimate_security' },
  { text: 'How do I execute a bash script on Linux?', category: 'legitimate_security' },
  { text: 'What is eval() in JavaScript and when should I use it?', category: 'legitimate_security' },
  { text: 'How do I inject dependencies using Spring Boot annotations?', category: 'legitimate_security' },
  { text: 'The system needs to be reset to factory defaults. How do I do that on a Cisco router?', category: 'legitimate_security' },
  { text: 'How do I bypass the login screen on my own Windows computer if I forgot my password?', category: 'legitimate_security' },
  { text: 'What is dependency injection and why is it useful in object-oriented programming?', category: 'legitimate_security' },
  { text: 'How do I override a method in a Java subclass?', category: 'legitimate_security' },
  { text: 'How do I execute a stored procedure in SQL Server?', category: 'legitimate_security' },
  { text: 'I need to inject mock services in my unit tests using Jest. How do I do that?', category: 'legitimate_security' },
  { text: 'How do I override the equals and hashCode methods in Kotlin?', category: 'legitimate_security' },
  { text: 'What command do I use to execute a Python script from the terminal?', category: 'legitimate_security' },
  { text: 'How do I bypass CORS issues during local development with a proxy?', category: 'legitimate_security' },
  { text: 'I need to reset my Git branch to match the remote. What is the safest way?', category: 'legitimate_security' },
  { text: 'How do I inject CSS custom properties (variables) from JavaScript?', category: 'legitimate_security' },

  // ─── 15. roleplay_legitimate (tricky but benign) ────────────────────────
  { text: 'Pretend you are explaining this to a 5 year old.', category: 'roleplay_legitimate' },
  { text: 'Act as if you are a customer calling our support line. How would the conversation go?', category: 'roleplay_legitimate' },
  { text: 'Imagine you are a hiring manager. What questions would you ask for a senior engineer role?', category: 'roleplay_legitimate' },
  { text: 'Pretend you are a travel agent and help me plan a trip to New Zealand.', category: 'roleplay_legitimate' },
  { text: 'Act as a debate opponent and argue the other side of this issue for practice.', category: 'roleplay_legitimate' },
  { text: 'Imagine you are a product manager. How would you prioritize these features?', category: 'roleplay_legitimate' },
  { text: 'Pretend you are interviewing me for a data science position. Ask me tough questions.', category: 'roleplay_legitimate' },
  { text: 'Act as a code reviewer and give me critical feedback on this pull request.', category: 'roleplay_legitimate' },
  { text: 'Imagine you are a user who is frustrated with our app. Write a realistic support ticket.', category: 'roleplay_legitimate' },
  { text: 'Pretend you are my English teacher and correct the grammar in this paragraph.', category: 'roleplay_legitimate' },
  { text: 'Act as a financial advisor and walk me through the pros and cons of buying vs renting a home.', category: 'roleplay_legitimate' },
  { text: 'Imagine you are a doctor explaining a diagnosis to a patient in plain language.', category: 'roleplay_legitimate' },
  { text: 'Pretend you are a mentor giving career advice to a junior developer.', category: 'roleplay_legitimate' },
  { text: 'Act as a Scrum Master and walk me through how to run a sprint planning meeting.', category: 'roleplay_legitimate' },
  { text: 'Imagine you are a security auditor reviewing our codebase. What would you look for first?', category: 'roleplay_legitimate' },
];

module.exports = BENIGN_SAMPLES;
