'use strict';

/**
 * Agent Shield — Dream → PR Bot
 *
 * Closes the dreaming loop: every cycle the DreamScheduler produces
 * change-request artifacts; this bot picks the latest high-confidence one
 * and converts it into a real PR. Branch name encodes provenance and
 * timestamp; PR body summarizes proposed patterns + threshold deltas +
 * incident clusters; draft by default so a human still merges.
 *
 * Three execution modes:
 *   - 'dry-run'     — emit { branch, title, body, files } only (default)
 *   - 'local-git'   — write files, create branch, commit, push via `git`
 *   - 'mcp-github'  — call MCP github tools to create branch + PR (host
 *                     supplies the callable adapter; we make no direct
 *                     network calls so this stays zero-dep + auditable)
 *
 * Generates two file artifacts when applying:
 *   - `dream-patches.json`        — newly proposed pattern entries
 *   - `dream-thresholds.json`     — tuned threshold map
 * The host's release workflow consumes these into the live detector or
 * config — Shield does not mutate detector-core directly so an unreviewed
 * dream can never live-fire.
 */

const path = require('path');
const fs = require('fs');

const DEFAULT_BRANCH_PREFIX = 'dream/auto';

class DreamPRBot {
  constructor(opts = {}) {
    this.memory = opts.memory;
    if (!this.memory) throw new Error('DreamPRBot requires { memory }');
    this.minConfidence = typeof opts.minConfidence === 'number' ? opts.minConfidence : 0.85;
    this.mode = opts.mode || 'dry-run';
    if (!['dry-run', 'local-git', 'mcp-github'].includes(this.mode)) {
      throw new Error(`unknown mode: ${this.mode}`);
    }
    this.branchPrefix = opts.branchPrefix || DEFAULT_BRANCH_PREFIX;
    this.repoRoot = opts.repoRoot || process.cwd();
    this.artifactDir = opts.artifactDir || path.join(this.repoRoot, 'config', 'dreams');
    this.mcpAdapter = opts.mcpAdapter || null; // { createBranch, putFile, openPR }
    this.gitRunner = opts.gitRunner || null;   // optional: async (args[]) => stdout
    this.draft = opts.draft !== false;
    this.history = [];
  }

  /**
   * Build a PR proposal from the latest change-request artifact. Returns
   * the full proposal object regardless of mode (mode only changes whether
   * we actually push/open).
   */
  async propose() {
    const cr = this.memory.loadLatestArtifact('change-request', { minConfidence: this.minConfidence });
    if (!cr) return { proposed: false, reason: `no change-request artifact above ${this.minConfidence} confidence` };
    const data = cr.data;
    const stamp = new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19);
    const branch = `${this.branchPrefix}/${stamp}-v${cr.version}`;
    const title = data.title || `[dream] auto-generated change request v${cr.version}`;
    const body = this._buildBody(data, cr);
    const files = this._buildFiles(data);

    const result = {
      proposed: true,
      mode: this.mode,
      version: cr.version,
      confidence: cr.confidence,
      branch,
      title,
      body,
      files: files.map((f) => ({ path: f.path, bytes: f.content.length })),
    };

    if (this.mode === 'dry-run') {
      result.dryRun = true;
    } else if (this.mode === 'local-git') {
      const applied = await this._applyLocal(branch, files, title, body);
      result.applied = applied;
    } else if (this.mode === 'mcp-github') {
      if (!this.mcpAdapter) throw new Error('mcp-github mode requires { mcpAdapter }');
      result.prUrl = await this._applyMcp(branch, files, title, body);
    }

    this.history.push({ at: Date.now(), branch, version: cr.version, mode: this.mode });
    return result;
  }

  _buildBody(data, cr) {
    const lines = [];
    lines.push(`## Summary`);
    lines.push(`Auto-generated by Agent Shield's dreaming subsystem (artifact \`change-request@${cr.version}\`, confidence ${cr.confidence.toFixed(2)}).`);
    lines.push('');
    if (Array.isArray(data.proposedPatterns) && data.proposedPatterns.length) {
      lines.push(`## Proposed detection patterns (${data.proposedPatterns.length})`);
      lines.push('');
      lines.push('| Category | Severity | FP rate | Regex |');
      lines.push('|---|---|---:|---|');
      for (const p of data.proposedPatterns) {
        lines.push(`| ${p.category} | ${p.severity} | ${typeof p.fpRate === 'number' ? (p.fpRate * 100).toFixed(1) + '%' : 'n/a'} | \`${(p.regexSource || '').slice(0, 80)}\` |`);
      }
      lines.push('');
    }
    if (data.thresholdProposal) {
      lines.push(`## Threshold retune (Δ F1 ${(data.thresholdProposal.delta || 0).toFixed(3)})`);
      lines.push('');
      lines.push('```json');
      lines.push(JSON.stringify(data.thresholdProposal.thresholds || {}, null, 2));
      lines.push('```');
      lines.push('');
    }
    if (Array.isArray(data.incidentClusters) && data.incidentClusters.length) {
      lines.push(`## Incident clusters analyzed (${data.incidentClusters.length})`);
      for (const c of data.incidentClusters.slice(0, 10)) {
        lines.push(`- **${c.key}** (${c.count} incidents)`);
      }
      lines.push('');
    }
    if (data.shadowDrift) {
      lines.push(`## Shadow-mode drift`);
      lines.push('');
      lines.push('```json');
      lines.push(JSON.stringify(data.shadowDrift, null, 2).slice(0, 600));
      lines.push('```');
      lines.push('');
    }
    lines.push(`## How this was generated`);
    lines.push(`Dream pipeline: ConsolidateIncidents → RetuneThresholds → EvolveAttacks → HuntNovelPatterns → ShadowDiffReplay → DraftSOCPatches. Every artifact above passed the configured FP-rate gate and confidence threshold (≥${this.minConfidence}).`);
    lines.push('');
    lines.push(`This PR is **draft by default**; merge only after manual review.`);
    return lines.join('\n');
  }

  _buildFiles(data) {
    const files = [];
    if (Array.isArray(data.proposedPatterns) && data.proposedPatterns.length) {
      files.push({
        path: path.join(this.artifactDir, 'dream-patches.json'),
        content: JSON.stringify({
          generatedAt: new Date().toISOString(),
          patterns: data.proposedPatterns,
        }, null, 2) + '\n',
      });
    }
    if (data.thresholdProposal) {
      files.push({
        path: path.join(this.artifactDir, 'dream-thresholds.json'),
        content: JSON.stringify({
          generatedAt: new Date().toISOString(),
          delta: data.thresholdProposal.delta || 0,
          thresholds: data.thresholdProposal.thresholds || {},
        }, null, 2) + '\n',
      });
    }
    return files;
  }

  async _applyLocal(branch, files, title, body) {
    const exec = this.gitRunner;
    if (!exec) throw new Error('local-git mode requires { gitRunner } (async (args[]) => stdout)');
    await exec(['checkout', '-b', branch]);
    for (const f of files) {
      const dir = path.dirname(f.path);
      try { fs.mkdirSync(dir, { recursive: true }); } catch (_) { /* ignore */ }
      fs.writeFileSync(f.path, f.content);
      await exec(['add', f.path]);
    }
    await exec(['commit', '-m', title, '-m', body]);
    // Push is host-policy-dependent; emit the branch name for the host to push.
    return { committed: true, branch, files: files.length };
  }

  async _applyMcp(branch, files, title, body) {
    const a = this.mcpAdapter;
    if (typeof a.createBranch !== 'function') throw new Error('mcpAdapter.createBranch required');
    if (typeof a.putFile !== 'function') throw new Error('mcpAdapter.putFile required');
    if (typeof a.openPR !== 'function') throw new Error('mcpAdapter.openPR required');
    await a.createBranch({ branch });
    for (const f of files) {
      await a.putFile({ branch, path: this._relative(f.path), content: f.content });
    }
    return await a.openPR({ branch, title, body, draft: this.draft });
  }

  _relative(absPath) {
    if (absPath.startsWith(this.repoRoot)) return absPath.slice(this.repoRoot.length + 1);
    return absPath;
  }

  stats() {
    return {
      mode: this.mode,
      proposalsMade: this.history.length,
      lastBranch: this.history[this.history.length - 1]?.branch || null,
    };
  }
}

module.exports = { DreamPRBot, DEFAULT_BRANCH_PREFIX };
